# Generated by Django 4.2.28 on 2026-02-19 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('francais', 'Français'), ('philosophie', 'Philosophie'), ('histoire', 'Histoire & Géo'), ('anglais', 'Anglais'), ('general', 'Général')], db_index=True, max_length=50)),
                ('enonce', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('reponse_correcte', models.CharField(max_length=300)),
                ('explication', models.TextField(blank=True)),
                ('sujet', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures_etude', models.FloatField(default=0)),
                ('exercices_resolus', models.PositiveIntegerField(default=0)),
                ('quiz_completes', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('francais', 'Français'), ('philosophie', 'Philosophie'), ('histoire', 'Histoire & Géo'), ('anglais', 'Anglais'), ('general', 'Général')], max_length=50)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=10)),
                ('details', models.JSONField(default=list)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('content', models.TextField()),
                ('subject', models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('francais', 'Français'), ('philosophie', 'Philosophie'), ('histoire', 'Histoire & Géo'), ('anglais', 'Anglais'), ('general', 'Général')], default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
