# Generated by Django 4.2.28 on 2026-02-19 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_flashcard_remove_userstats_heures_etude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('erreur', 'Erreur récurrente'), ('force', 'Point fort'), ('style', "Style d'apprentissage"), ('perso', 'Info personnelle'), ('progression', 'Progression notable'), ('concept', 'Concept mal compris'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField()),
                ('tag', models.CharField(blank=True, db_index=True, max_length=100)),
                ('importance', models.IntegerField(default=5)),
                ('seen_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-importance', '-updated_at'],
                'unique_together': {('user', 'tag')},
            },
        ),
    ]
