# Generated by Django 4.2.28 on 2026-02-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_ai_memory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, max_length=50)),
                ('filename', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('text_excerpt', models.TextField()),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('indexed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', 'filename'],
                'unique_together': {('subject', 'filename')},
            },
        ),
    ]
