# Generated by Django 5.2.11 on 2026-02-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subjectchapter_coursesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='minutes_etude',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='subject',
            field=models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('philosophie', 'Philosophie'), ('histoire', 'Histoire & Géo'), ('anglais', 'Anglais'), ('general', 'Général')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='subject',
            field=models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('philosophie', 'Philosophie'), ('histoire', 'Histoire & Géo'), ('anglais', 'Anglais'), ('general', 'Général')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='subject',
            field=models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('philosophie', 'Philosophie'), ('histoire', 'Histoire & Géo'), ('anglais', 'Anglais'), ('general', 'Général')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='subject',
            field=models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('philosophie', 'Philosophie'), ('histoire', 'Histoire & Géo'), ('anglais', 'Anglais'), ('general', 'Général')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectchapter',
            name='subject',
            field=models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('philosophie', 'Philosophie'), ('histoire', 'Histoire & Géo'), ('anglais', 'Anglais'), ('general', 'Général')], db_index=True, max_length=50),
        ),
    ]
