# Generated by Django 5.2.11 on 2026-02-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userstats_minutes_etude_alter_chatmessage_subject_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectchapter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subjectchapter',
            name='subsection',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='subjectchapter',
            unique_together={('subject', 'subsection', 'title')},
        ),
    ]
