# Generated by Django 5.2.11 on 2026-02-22 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subjectchapter_subsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='chapter_desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='chapter_num',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='chapter_subject',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='chapter_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.subjectchapter'),
        ),
    ]
