# Generated by Django 4.2.28 on 2026-02-28 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_json_course_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='subject',
            field=models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('francais', 'Français'), ('philosophie', 'Philosophie'), ('histoire', 'Histoire & Géo'), ('anglais', 'Anglais'), ('general', 'Général')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='subject',
            field=models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('francais', 'Français'), ('philosophie', 'Philosophie'), ('histoire', 'Histoire & Géo'), ('anglais', 'Anglais'), ('general', 'Général')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='subject',
            field=models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('francais', 'Français'), ('philosophie', 'Philosophie'), ('histoire', 'Histoire & Géo'), ('anglais', 'Anglais'), ('general', 'Général')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='subject',
            field=models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('francais', 'Français'), ('philosophie', 'Philosophie'), ('histoire', 'Histoire & Géo'), ('anglais', 'Anglais'), ('general', 'Général')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectchapter',
            name='subject',
            field=models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('francais', 'Français'), ('philosophie', 'Philosophie'), ('histoire', 'Histoire & Géo'), ('anglais', 'Anglais'), ('general', 'Général')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='MistakeTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, max_length=50)),
                ('question_hash', models.CharField(db_index=True, max_length=32)),
                ('enonce', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('reponse_correcte', models.IntegerField(default=0)),
                ('explication', models.TextField(blank=True)),
                ('theme', models.CharField(blank=True, max_length=100)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.PositiveSmallIntegerField(default=1)),
                ('repetitions', models.PositiveSmallIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=1)),
                ('correct_streak', models.PositiveSmallIntegerField(default=0)),
                ('mastered', models.BooleanField(db_index=True, default=False)),
                ('next_review', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_review'],
                'indexes': [models.Index(fields=['user', 'mastered', 'next_review'], name='core_mistak_user_id_15a716_idx')],
                'unique_together': {('user', 'question_hash')},
            },
        ),
    ]
