# Generated by Django 4.2.28 on 2026-03-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mistake_tracker_sm2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='subject',
            field=models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('francais', 'Kreyòl'), ('philosophie', 'Philosophie'), ('histoire', 'Histoire & Géo'), ('anglais', 'Anglais'), ('general', 'Général')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='subject',
            field=models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('francais', 'Kreyòl'), ('philosophie', 'Philosophie'), ('histoire', 'Histoire & Géo'), ('anglais', 'Anglais'), ('general', 'Général')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='subject',
            field=models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('francais', 'Kreyòl'), ('philosophie', 'Philosophie'), ('histoire', 'Histoire & Géo'), ('anglais', 'Anglais'), ('general', 'Général')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='subject',
            field=models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('francais', 'Kreyòl'), ('philosophie', 'Philosophie'), ('histoire', 'Histoire & Géo'), ('anglais', 'Anglais'), ('general', 'Général')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectchapter',
            name='subject',
            field=models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('francais', 'Kreyòl'), ('philosophie', 'Philosophie'), ('histoire', 'Histoire & Géo'), ('anglais', 'Anglais'), ('general', 'Général')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source_text', models.TextField()),
                ('translated', models.TextField()),
                ('lang', models.CharField(default='kr', max_length=10)),
                ('context', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['content_hash', 'lang'], name='core_transl_content_55a1c3_idx')],
            },
        ),
    ]
