# Generated by Django 5.2.11 on 2026-03-28 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_generatedcourseasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcourseasset',
            name='asset_type',
            field=models.CharField(choices=[('lesson', 'Lecon'), ('quiz', 'Mini quiz'), ('exercise_bank', 'Banque exercices')], max_length=20),
        ),
        migrations.CreateModel(
            name='BACExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_file', models.CharField(max_length=255)),
                ('exam_year', models.CharField(max_length=4)),
                ('exam_series', models.CharField(max_length=50)),
                ('problem_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('theme', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bac_exercises', to='core.subjectchapter')),
            ],
            options={
                'ordering': ['chapter', 'exam_year', 'problem_number'],
                'indexes': [models.Index(fields=['chapter', 'theme'], name='core_bacexe_chapter_b40c76_idx'), models.Index(fields=['exam_year'], name='core_bacexe_exam_ye_b5ee88_idx')],
            },
        ),
    ]
