# Generated by Django 5.2.11 on 2026-04-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_generatedcourseasset_asset_type_bacexercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcourseasset',
            name='asset_type',
            field=models.CharField(choices=[('lesson', 'Lecon'), ('quiz', 'Mini quiz'), ('exercise_bank', 'Banque exercices'), ('summary', 'Résumé chapitre')], max_length=20),
        ),
    ]
