# Generated by Django 5.2.11 on 2026-04-03 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_generatedcourseasset_asset_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, max_length=50)),
                ('chapter', models.CharField(blank=True, max_length=200)),
                ('exercise_hash', models.CharField(db_index=True, max_length=32)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('score', models.FloatField(blank=True, null=True)),
                ('done_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-done_at'],
                'indexes': [models.Index(fields=['user', 'subject', 'chapter'], name='core_exerci_user_id_980336_idx'), models.Index(fields=['user', 'exercise_hash'], name='core_exerci_user_id_68c679_idx'), models.Index(fields=['user', 'subject', 'done_at'], name='core_exerci_user_id_4dec6d_idx')],
            },
        ),
    ]
