# Generated by Django 4.2.28 on 2026-04-05 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_exercise_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizDuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('subject', models.CharField(max_length=50)),
                ('questions', models.JSONField(default=list)),
                ('creator_answers', models.JSONField(default=list)),
                ('challenger_answers', models.JSONField(default=list)),
                ('creator_score', models.IntegerField(default=0)),
                ('challenger_score', models.IntegerField(default=0)),
                ('creator_finished', models.BooleanField(default=False)),
                ('challenger_finished', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('waiting', 'En attente du challenger'), ('active', 'En cours'), ('finished', 'Terminé'), ('expired', 'Expiré')], default='waiting', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('challenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duels_joined', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='subject',
            field=models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('francais', 'Kreyòl'), ('philosophie', 'Philosophie'), ('anglais', 'Anglais'), ('general', 'Général')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='subject',
            field=models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('francais', 'Kreyòl'), ('philosophie', 'Philosophie'), ('anglais', 'Anglais'), ('general', 'Général')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='subject',
            field=models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('francais', 'Kreyòl'), ('philosophie', 'Philosophie'), ('anglais', 'Anglais'), ('general', 'Général')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='subject',
            field=models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('francais', 'Kreyòl'), ('philosophie', 'Philosophie'), ('anglais', 'Anglais'), ('general', 'Général')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectchapter',
            name='subject',
            field=models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('francais', 'Kreyòl'), ('philosophie', 'Philosophie'), ('anglais', 'Anglais'), ('general', 'Général')], db_index=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='ExerciseHistory',
        ),
    ]
