# Generated by Django 4.2.28 on 2026-04-07 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_quiz_duel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('mastery_score', models.FloatField(default=0.0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('avg_time_seconds', models.FloatField(blank=True, null=True)),
                ('confidence_level', models.CharField(choices=[('debutant', 'Débutant'), ('apprenti', 'Apprenti'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('expert', 'Expert')], default='debutant', max_length=20)),
                ('recent_errors', models.JSONField(default=list)),
                ('recent_correct', models.JSONField(default=list)),
                ('mastered_topics', models.JSONField(default=list)),
                ('weak_topics', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_masteries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-mastery_score'],
                'unique_together': {('user', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('quiz_completed', 'Quiz complété'), ('exercise_corrected', 'Exercice corrigé'), ('chat_session', 'Session de chat'), ('course_chapter', 'Chapitre de cours'), ('mastery_gained', 'Maîtrise acquise')], max_length=30)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('score_pct', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'subject', 'event_type'], name='core_learni_user_id_680681_idx'), models.Index(fields=['user', 'created_at'], name='core_learni_user_id_e1ce59_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatSessionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('summary', models.JSONField(default=dict)),
                ('subjects_covered', models.JSONField(default=list)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'session_key')},
            },
        ),
    ]
