# Generated by Django 4.2.28 on 2026-04-12 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_extrabetpost_extrabetattempt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='extrabetpost',
            new_name='core_extrab_subject_c15bcf_idx',
            old_name='core_extrabe_subject_c2dfda_idx',
        ),
        migrations.AddField(
            model_name='extrabetpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_extra_bets', to=settings.AUTH_USER_MODEL),
        ),
    ]
