# Generated by Django 4.2.28 on 2026-05-10 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_add_aiprogresscache'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, max_length=50)),
                ('serie', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('exam_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seen_by', models.ManyToManyField(blank=True, related_name='seen_generated_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject', 'serie'], name='core_genera_subject_0eb768_idx')],
            },
        ),
    ]
