# Generated by Django 6.0.7 on 2026-08-12 09:07

import core.r2_storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_ai_usage_daily'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('VIDEO', 'VIDEO'), ('IMAGE', 'IMAGE'), ('QUIZ', 'QUIZ')], db_index=True, max_length=8)),
                ('media_file', models.FileField(blank=True, null=True, storage=core.r2_storage.R2MediaStorage(), upload_to='feed/')),
                ('caption', models.TextField(blank=True, default='')),
                ('quiz_item_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('subject', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='aiusagedaily',
            new_name='core_aiusag_date_1092a1_idx',
            old_name='core_aiusag_date_fe_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagedaily',
            new_name='core_aiusag_user_id_fcb8cb_idx',
            old_name='core_aiusag_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='userseenexamitem',
            new_name='core_userse_user_id_064bcb_idx',
            old_name='core_userse_user_id_8a3f21_idx',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type', 'created_at'], name='core_post_post_ty_bfb039_idx'),
        ),
    ]
