# Generated by Django 6.0.7 on 2026-08-12 09:40

import core.r2_storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_friendship_userfollow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('sticker', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostCommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach_type', models.CharField(choices=[('IMAGE', 'IMAGE'), ('VOICE', 'VOICE')], db_index=True, max_length=8)),
                ('file', models.FileField(blank=True, null=True, storage=core.r2_storage.R2MediaStorage(location_override='comment_media'), upload_to='comments/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.postcomment')),
            ],
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['post', 'created_at'], name='core_postco_post_id_9cee79_idx'),
        ),
        migrations.AddIndex(
            model_name='postcommentattachment',
            index=models.Index(fields=['comment', 'attach_type', 'created_at'], name='core_postco_comment_6616c8_idx'),
        ),
    ]
