# Generated by Django 6.0.7 on 2026-08-30 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeniusCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('registration', 'registration'), ('roster_locked', 'roster_locked'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('prizes', models.JSONField(blank=True, default=dict)),
                ('subjects', models.JSONField(blank=True, default=list)),
                ('max_teams', models.PositiveIntegerField(default=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genius_competitions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeniusMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('lobby', 'lobby'), ('in_progress', 'in_progress'), ('finished', 'finished'), ('forfeit', 'forfeit'), ('cancelled', 'cancelled')], default='scheduled', max_length=20)),
                ('phase', models.CharField(choices=[('waiting', 'waiting'), ('question_show', 'question_show'), ('answering', 'answering'), ('captain_lock', 'captain_lock'), ('revealing', 'revealing'), ('explanation', 'explanation'), ('finished', 'finished')], default='waiting', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('team_a_score', models.IntegerField(default=0)),
                ('team_b_score', models.IntegerField(default=0)),
                ('current_question_index', models.PositiveSmallIntegerField(default=0)),
                ('phase_deadline', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('forfeit_reason', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='genius.geniuscompetition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeniusTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=240)),
                ('emblem_emoji', models.CharField(blank=True, default='🧠', max_length=8)),
                ('invite_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genius_teams_captained', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeniusMatchQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('subject', models.CharField(blank=True, default='', max_length=50)),
                ('question_type', models.CharField(choices=[('team', 'Équipe'), ('individual', 'Individuel')], default='team', max_length=12)),
                ('question_data', models.JSONField(default=dict)),
                ('correct_choice', models.CharField(blank=True, default='', max_length=4)),
                ('final_choice', models.CharField(blank=True, default='', max_length=4)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_awarded', models.IntegerField(default=0)),
                ('revealed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='genius.geniusmatch')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genius_target_questions', to=settings.AUTH_USER_MODEL)),
                ('responding_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_questions', to='genius.geniusteam')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('match', 'index')},
            },
        ),
        migrations.CreateModel(
            name='GeniusMatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='genius.geniusmatch')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genius.geniusteam')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='geniusmatch',
            name='forfeit_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forfeit_matches', to='genius.geniusteam'),
        ),
        migrations.AddField(
            model_name='geniusmatch',
            name='responding_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_matches', to='genius.geniusteam'),
        ),
        migrations.AddField(
            model_name='geniusmatch',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to='genius.geniusteam'),
        ),
        migrations.AddField(
            model_name='geniusmatch',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to='genius.geniusteam'),
        ),
        migrations.AddField(
            model_name='geniusmatch',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_wins', to='genius.geniusteam'),
        ),
        migrations.CreateModel(
            name='GeniusInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('cancelled', 'cancelled'), ('expired', 'expired')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genius_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genius_invites_received', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='genius.geniusteam')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeniusBracketNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_key', models.CharField(db_index=True, max_length=40)),
                ('phase_label', models.CharField(blank=True, default='', max_length=80)),
                ('round_order', models.PositiveSmallIntegerField(default=0)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='genius.geniusbracketnode')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracket_nodes', to='genius.geniuscompetition')),
                ('match', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_node', to='genius.geniusmatch')),
                ('team_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_as_a', to='genius.geniusteam')),
                ('team_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_as_b', to='genius.geniusteam')),
                ('winner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_wins', to='genius.geniusteam')),
            ],
            options={
                'ordering': ['round_order', 'position'],
            },
        ),
        migrations.CreateModel(
            name='GeniusRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('registered', 'Inscrite'), ('roster_locked', 'Roster verrouillé'), ('eliminated', 'Éliminée'), ('withdrawn', 'Retirée')], default='pending', max_length=20)),
                ('roster_locked_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('eliminated_at', models.DateTimeField(blank=True, null=True)),
                ('current_phase_key', models.CharField(blank=True, default='', max_length=40)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='genius.geniuscompetition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_regs', to='genius.geniusteam')),
            ],
            options={
                'ordering': ['registered_at'],
                'unique_together': {('competition', 'team')},
            },
        ),
        migrations.CreateModel(
            name='GeniusMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('captain', 'Capitaine'), ('member', 'Membre')], default='member', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('left', 'Parti'), ('removed', 'Retiré')], default='active', max_length=10)),
                ('consecutive_missed', models.PositiveSmallIntegerField(default=0)),
                ('removal_eligible', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genius_memberships', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='genius.geniusteam')),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GeniusMatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='genius.geniusmatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genius.geniusteam')),
            ],
            options={
                'unique_together': {('match', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GeniusVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='genius.geniusmatchquestion')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genius.geniusteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('match_question', 'user')},
            },
        ),
    ]
