# Generated by Django 6.0.7 on 2026-08-30 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genius', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeniusTeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('ranking_points', models.PositiveIntegerField(default=0)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='genius.geniusteam')),
            ],
            options={
                'ordering': ['-ranking_points', '-wins', '-total_score'],
            },
        ),
        migrations.CreateModel(
            name='GeniusNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('invite', 'Invitation équipe'), ('challenge', 'Défi reçu'), ('match_ready', 'Match à jouer'), ('match_result', 'Résultat match'), ('competition_start', 'Concours lancé'), ('bracket_ready', 'Bracket publié')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(blank=True, default='', max_length=280)),
                ('link_path', models.CharField(blank=True, default='', max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genius.geniuscompetition')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genius.geniusmatch')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genius.geniusteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genius_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at', '-created_at'], name='genius_geni_user_id_788d51_idx')],
            },
        ),
    ]
