# Generated by Django 4.2.28 on 2026-02-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='serie',
            field=models.CharField(blank=True, choices=[('SVT', 'SVT — Sciences de la Vie et de la Terre'), ('SMP', 'SMP — Sciences Mathématiques et Physiques'), ('SES', 'SES — Sciences Économiques et Sociales'), ('LLA', 'LLA — Lettres, Langues et Arts')], default='SVT', max_length=3),
        ),
    ]
