# Generated by Django 5.2.11 on 2026-02-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticresult',
            name='subject',
            field=models.CharField(choices=[('maths', 'Maths'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('svt', 'SVT'), ('philosophie', 'Philosophie'), ('histoire', 'Histoire & Géo'), ('anglais', 'Anglais')], max_length=50),
        ),
    ]
