# Generated by Django 4.2.28 on 2026-03-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_diagnosticresult_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_lang',
            field=models.CharField(choices=[('fr', 'Français'), ('kr', 'Kreyòl')], default='fr', max_length=5),
        ),
    ]
