# Generated by Django 4.2.28 on 2026-04-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_agent_agentreferral_agentwithdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bac_target',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Note cible sur 1900 définie à l'inscription", null=True),
        ),
    ]
