# Generated by Django 4.2.28 on 2026-04-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_persistentauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_session_key',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='device_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='device_user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_device',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
