# Generated by Django 4.2.28 on 2026-04-12 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_cloudinary_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plan_expiration',
            field=models.DateField(blank=True, help_text="Date d'expiration de l'abonnement actif", null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('plan', models.CharField(choices=[('monthly', 'Mensuel'), ('annual', 'Annuel')], max_length=10)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Payé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
