# Generated by Django 4.2.28 on 2026-04-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_admin_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentreferral',
            name='amount',
            field=models.PositiveIntegerField(default=150),
        ),
    ]
