# Generated by Django 4.2.30 on 2026-04-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_adminpanelconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendmessage',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
