# Generated by Django 4.2.30 on 2026-04-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_friendmessage_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyusage',
            name='extra_bet_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
