# Generated by Django 4.2.28 on 2026-05-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_dailyusage_extra_bet_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentreferral',
            name='amount',
            field=models.PositiveIntegerField(default=750),
        ),
    ]
