# Generated by Django 4.2.28 on 2026-05-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_commission_750g'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftpaymentlink',
            name='student_contact',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
