# Generated by Codex on 2026-05-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0026_messagedeletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='mention_everyone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='accounts.groupmessage'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_group_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GroupMessageNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('reply', 'Réponse'), ('mention', 'Mention'), ('everyone', 'Mention tout le monde')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.groupmessage')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_message_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('message', 'recipient', 'reason')},
                'indexes': [
                    models.Index(fields=['recipient', 'is_read'], name='accounts_gr_recipient_151a45_idx'),
                    models.Index(fields=['message', 'recipient'], name='accounts_gr_message_bfe7a6_idx'),
                ],
            },
        ),
    ]
