from django.urls import path
from . import views
from .admin_panel import (
    admin_login_view, admin_panel_view, admin_logout_view,
    api_admin_withdrawal, api_admin_send_message, api_admin_users,
    api_admin_stats_chart,
)

urlpatterns = [
    # ── Secret Admin Panel ──
    path('otb-ctrl-9x7k/',          admin_panel_view,       name='admin_panel'),
    path('otb-ctrl-9x7k/login/',    admin_login_view,       name='admin_panel_login'),
    path('otb-ctrl-9x7k/logout/',   admin_logout_view,      name='admin_panel_logout'),
    path('otb-ctrl-9x7k/api/withdrawal/', api_admin_withdrawal, name='admin_api_withdrawal'),
    path('otb-ctrl-9x7k/api/message/',    api_admin_send_message, name='admin_api_send_msg'),
    path('otb-ctrl-9x7k/api/users/',      api_admin_users,        name='admin_api_users'),
    path('otb-ctrl-9x7k/api/stats/',      api_admin_stats_chart,  name='admin_api_stats_chart'),

    path('',              views.dashboard,          name='dashboard'),
    path('guest/start/',  views.start_guest_view,   name='guest_start'),
    path('guest/stop/',   views.stop_guest_view,    name='guest_stop'),
    path('chat/',         views.chat_view,           name='chat'),
    path('quiz/',         views.quiz_view,           name='quiz'),
    path('extra-bet/',    views.extra_bet_view,      name='extra_bet'),
    path('exercices/',    views.exercices_view,      name='exercices'),
    path('progression/',  views.progression_view,    name='progression'),
    path('profil/',       views.profil_view,         name='profil'),
    path('api/avatar/upload/', views.api_avatar_upload, name='api_avatar_upload'),

    # Nouvelles pages
    path('historique/',   views.historique_view,       name='historique'),
    path('historique/<str:session_key>/', views.conversation_detail, name='conversation_detail'),
    path('fiches/',       views.fiches_view,            name='fiches'),
    path('plan/',         views.plan_view,              name='plan'),
    path('bookmarks/',    views.bookmarks_view,         name='bookmarks'),

    # API endpoints (AJAX)
    path('api/chat/',              views.chat_api,              name='api_chat'),
    path('api/chat/session/',      views.api_load_session,      name='api_load_session'),
    path('api/quiz/questions/',    views.quiz_questions_api,    name='api_quiz_questions'),
    path('api/extra-bet/create/',  views.api_extra_bet_create,  name='api_extra_bet_create'),
    path('api/extra-bet/answer/',  views.api_extra_bet_answer,  name='api_extra_bet_answer'),
    path('api/extra-bet/ai-help/', views.api_extra_bet_ai_help, name='api_extra_bet_ai_help'),
    path('api/extra-bet/like/',    views.api_extra_bet_like,    name='api_extra_bet_like'),
    path('api/extra-bet/delete/',  views.api_extra_bet_delete,  name='api_extra_bet_delete'),
    path('api/quiz/save/',         views.quiz_save_api,         name='api_quiz_save'),
    path('api/quiz/analyse/',      views.api_analyse_quiz,      name='api_analyse_quiz'),
    path('api/solve/',             views.solve_api,             name='api_solve'),
    path('api/exercices/get/',     views.api_get_exercise,      name='api_get_exercise'),
    path('api/exercices/analyze/', views.api_analyze_exercise,  name='api_analyze_exercise'),
    path('api/exercices/correct/',  views.api_correct_exercise,  name='api_correct_exercise'),
    path('api/exercices/teach/',    views.api_teach_exercise,    name='api_teach_exercise'),
    path('api/exercices/similar/',  views.api_similar_exercise,  name='api_similar_exercise'),
    path('api/exercices/chat/',     views.api_exercise_chat,     name='api_exercise_chat'),
    path('api/exercices/complete/', views.api_exercise_complete, name='api_exercise_complete'),
    path('api/exam/ai-correct/',    views.api_exam_ai_correct,   name='api_exam_ai_correct'),
    path('api/fiches/generate/',   views.api_generate_fiches,   name='api_generate_fiches'),
    path('api/fiches/status/',     views.api_flashcard_status,  name='api_flashcard_status'),
    path('api/plan/generate/',     views.api_generate_plan,     name='api_generate_plan'),
    path('api/bookmark/',          views.api_bookmark_toggle,   name='api_bookmark'),
    path('api/stats/',             views.api_stats,             name='api_stats'),
    path('api/guest/set-serie/',   views.api_guest_set_serie,   name='api_guest_set_serie'),
    path('api/demo-qa/refresh/',   views.api_refresh_demo_qa,   name='api_refresh_demo_qa'),
    path('api/study/ping/',        views.study_ping,            name='api_study_ping'),
    path('api/coaching/',          views.api_coaching,          name='api_coaching'),
    path('api/coaching/cards/',    views.api_coaching_cards,    name='api_coaching_cards'),
    path('api/chat/suggestions/',  views.api_chat_suggestions,  name='api_chat_suggestions'),
    path('api/smart-coach/',       views.api_smart_coach,       name='api_smart_coach'),
    path('api/mistakes/summary/',  views.api_mistakes_summary,  name='api_mistakes_summary'),

    # Examen blanc
    path('examen-blanc/',               views.examen_blanc_view,           name='examen_blanc'),
    path('api/examen-blanc/questions/', views.api_examen_blanc_questions,  name='api_examen_blanc_questions'),
    path('api/examen-blanc/generate/',  views.api_generate_exam,           name='api_generate_exam'),
    path('api/examen-blanc/generate-v2/', views.api_generate_exam_v2,      name='api_generate_exam_v2'),

    # Cours interactif
    path('cours/',                              views.cours_view,          name='cours'),
    path('cours/sc-social/',                    views.sc_social_view,      name='sc_social'),
    path('cours/physique/',                     views.physique_view,       name='physique_course'),
    path('cours/math/',                         views.math_cours_view,     name='math_cours'),
    path('cours/svt/',                          views.svt_cours_view,      name='svt_cours'),
    path('cours/kreyol/',                       views.kreyol_cours_view,   name='kreyol_cours'),
    path('cours/chimie/',        views.chimie_cours_view,       name='chimie_cours'),
    path('cours/anglais/',       views.anglais_cours_view,      name='anglais_cours'),
    path('cours/economie/',      views.economie_cours_view,     name='economie_cours'),
    path('cours/histoire/',      views.histoire_cours_view,     name='histoire_cours'),
    path('cours/informatique/',  views.informatique_cours_view, name='informatique_cours'),
    path('cours/art/',           views.art_cours_view,          name='art_cours'),
    path('cours/espagnol/',      views.espagnol_cours_view,     name='espagnol_cours'),
    path('cours/philosophie/',   views.philosophie_cours_view,  name='philosophie_cours'),
    path('amis/',                views.amis_view,               name='amis'),
    path('api/amis/',            views.api_friend_request,      name='api_friend_request'),
    path('api/amis/messages/<int:friend_id>/', views.api_friend_messages, name='api_friend_messages'),
    path('api/amis/send/',       views.api_friend_send_message, name='api_friend_send_message'),
    path('api/amis/unread/',     views.api_friend_unread_count, name='api_friend_unread_count'),
    path('api/admin-message/',   views.api_admin_message,       name='api_admin_message'),

    # Duel en ligne
    path('duel/',                  views.duel_view,        name='duel'),
    path('api/duel/create/',       views.api_duel_create,  name='api_duel_create'),
    path('api/duel/join/',         views.api_duel_join,    name='api_duel_join'),
    path('api/duel/state/',        views.api_duel_state,   name='api_duel_state'),
    path('api/duel/finish/',       views.api_duel_finish,  name='api_duel_finish'),
    path('cours/physique/exercices/<str:section_id>/', views.physique_exercises_view, name='physique_exercises_page'),
    path('cours/physique/exercices/<str:section_id>/<int:exercise_index>/', views.physique_exercise_detail_view, name='physique_exercise_detail_page'),
    path('cours/physique/exercices/<str:section_id>/<int:exercise_index>/similar/', views.physique_exercise_similar_view, name='physique_exercise_similar_page'),
    path('cours/<str:subject>/<int:num>/',      views.chapter_cours_view,  name='chapter_cours'),
    path('api/cours/chat/',                     views.api_course_chat,     name='api_course_chat'),
    path('api/cours/hybrid-progress/',          views.api_course_hybrid_progress, name='api_course_hybrid_progress'),
    path('api/cours/reset/',                    views.api_course_reset,    name='api_course_reset'),
    path('api/cours/section/',                  views.api_course_section,  name='api_course_section'),
    path('api/cours/miniquiz/',                 views.api_course_miniquiz, name='api_course_miniquiz'),
    path('api/course-question/',                views.api_course_question, name='api_course_question'),
    path('api/chapter-summary/',                views.api_chapter_summary, name='api_chapter_summary'),
    path('api/generate-exercises/',             views.api_generate_exercises, name='api_generate_exercises'),
    path('api/cours/physique/section/',         views.api_physique_section, name='api_physique_section'),
    path('api/cours/physique/miniquiz/',        views.api_physique_miniquiz, name='api_physique_miniquiz'),
    path('api/cours/physique/exercises/',       views.api_physique_exercises, name='api_physique_exercises'),
    path('api/cours/physique/progress/',        views.api_physique_progress, name='api_physique_progress'),
    path('api/cours/sc-social/progress/',       views.api_sc_social_progress, name='api_sc_social_progress'),
    path('api/cours/sc-social/correct/',        views.api_sc_social_correct, name='api_sc_social_correct'),
    
    # Traduction
    path('api/translate/',   views.api_translate,   name='api_translate'),
    path('api/user-lang/',   views.api_user_lang,   name='api_user_lang'),

    # Bibliothèque PDF
    path('library/',               views.library_view,           name='library'),
    path('api/pdf-serve/',         views.api_pdf_serve,          name='api_pdf_serve'),
    path('api/pdf-extract-text/',  views.api_pdf_extract_text,   name='api_pdf_extract_text'),
]
