"""Art plastique et technologie / informatique 9e AF."""
from __future__ import annotations

import random

from .common import make_q, shuffle_wrong_options, bank_to_questions

ART = [
    ("Couleur primaire (tradition peinture):", "rouge", ["vert", "orange", "violet"], "Primaires: R, J, B."),
    ("Couleur primaire:", "jaune", ["violet", "orange", "marron"], "Jaune primaire."),
    ("Couleur primaire:", "bleu", ["vert", "orange", "marron"], "Bleu primaire."),
    ("Rouge + jaune =", "orange", ["vert", "violet", "marron"], "Secondaire."),
    ("Bleu + jaune =", "vert", ["orange", "violet", "marron"], "Secondaire."),
    ("Rouge + bleu =", "violet", ["vert", "orange", "marron"], "Secondaire."),
    ("Couleurs chaudes:", "rouge, orange, jaune", ["bleu, vert", "noir, blanc", "gris seul"], "Chaudes."),
    ("Couleurs froides:", "bleu, vert, violet", ["rouge, orange", "noir seul", "blanc seul"], "Froides."),
    ("Complémentaires: rouge /", "vert", ["bleu", "jaune", "orange"], "Opposés cercle."),
    ("Complémentaires: bleu /", "orange", ["vert", "rouge", "violet"], "Opposés."),
    ("Teinte =", "couleur pure", ["noir", "blanc", "gris"], "Hue."),
    ("Saturation =", "intensité couleur", ["taille", "forme", "texture"], "Saturation."),
    ("Valeur =", "clair ou foncé", ["longueur", "largeur", "poids"], "Value."),
    ("Ligne horizontale suggère:", "calme, stabilité", ["mouvement rapide", "danger", "chaos"], "Horizontal."),
    ("Ligne verticale suggère:", "force, hauteur", ["calme seul", "horizontal", "cercle"], "Vertical."),
    ("Ligne diagonale suggère:", "mouvement, dynamisme", ["calme", "stabilité", "immobilité"], "Diagonal."),
    ("Forme géométrique: cercle =", "continuité", ["chaos", "rupture", "angle"], "Circle."),
    ("Forme organique:", "naturelle, irrégulière", ["géométrique", "carrée", "triangulaire"], "Organic."),
    ("Texture visuelle:", "apparence surface", ["odeur", "son", "taste"], "Texture."),
    ("Perspective: point de", "fuite", ["départ", "milieu", "fin"], "Vanishing point."),
    ("Proportion =", "rapport des tailles", ["couleur seule", "odeur", "son"], "Proportion."),
    ("Échelle =", "taille relative", ["couleur", "odeur", "son"], "Scale."),
    ("Contraste fort =", "opposition marquée", ["uniformité", "monotone", "identique"], "Contrast."),
    ("Harmonie =", "accord des éléments", ["chaos", "désordre", "rupture"], "Harmony."),
    ("Rythme visuel =", "répétition motif", ["silence", "odeur", "taste"], "Rhythm."),
    ("Balance symétrique:", "miroir", ["chaos", "désordre", "aléatoire"], "Symmetry."),
    ("Balance asymétrique:", "équilibre dynamique", ["miroir exact", "identique", "copie"], "Asymmetry."),
    ("Composition: règle des", "tiers", ["cinquièmes", "dixièmes", "centièmes"], "Rule of thirds."),
    ("Focal point =", "point d'attention", ["bord", "coin", "arrière"], "Focus."),
    ("Négatif (espace) =", "zone vide autour sujet", ["couleur", "odeur", "son"], "Negative space."),
    ("Sculpture 3D vs peinture", "2D", ["1D", "4D", "0D"], "Dimensions."),
    ("Modelage: argile,", "plâtre", ["eau seule", "air seul", "feu seul"], "Modeling."),
    ("Taille directe: pierre,", "bois", ["papier seul", "digital seul", "air"], "Carving."),
    ("Gravure imprime depuis", "plaque", ["toile", "mur", "sol"], "Printmaking."),
    ("Sérigraphie =", "impression à pochoir", ["sculpture", "danse", "musique"], "Screen print."),
    ("Aquarelle: peinture à l'", "eau", ["huile seule", "acrylique seule", "encre seule"], "Watercolor."),
    ("Acrylique sèche", "rapidement", ["jamais", "en 10 ans", "en 100 ans"], "Acrylic."),
    ("Huile sèche", "lentement", ["instant", "1 seconde", "0 seconde"], "Oil paint."),
    ("Fresque peint sur", "mur humide", ["papier sec", "toile sèche", "bois sec"], "Fresco."),
    ("Gouache =", "peinture opaque à l'eau", ["huile", "acrylique", "cire"], "Gouache."),
    ("Encre de Chine:", "noir intense", ["blanc", "transparent", "invisible"], "India ink."),
    ("Fusain =", "crayon charbon", ["aquarelle", "huile", "acrylique"], "Charcoal."),
    ("Pastel:", "pigment + liant", ["eau pure", "air pur", "métal pur"], "Pastel."),
    ("Collage =", "assemblage matériaux", ["destruction", "effacement", "censure"], "Collage."),
    ("Pop art: Andy", "Warhol", ["Picasso seul", "Van Gogh seul", "Monet seul"], "Warhol."),
    ("Cubisme: Picasso,", "Braque", ["Warhol", "Monet", "Raphael"], "Cubism."),
    ("Impressionnisme: Monet,", "Renoir", ["Picasso cubiste", "Warhol", "Banksy"], "Impressionism."),
    ("Surréalisme: Salvador", "Dalí", ["Monet", "Warhol", "Michel-Ange seul"], "Surrealism."),
    ("Art abstrait ne représente pas", "réel identifiable", ["toujours réel", "photo", "copie"], "Abstract."),
    ("Art figuratif représente", "monde visible", ["rien", "vide", "chaos seul"], "Figurative."),
    ("Street art / graffiti souvent en", "ville", ["océan", "espace", "lune"], "Urban art."),
    ("Banksy: art", "urbain", ["classique", "romain", "grec seul"], "Street artist."),
    ("Architecture: fonction et", "forme", ["odeur", "taste", "son seul"], "Form follows function."),
    ("Colonne grecque: Dorique,", "Ionique, Corinthien", ["Roman seul", "Aztec", "Inca"], "Orders."),
    ("Pyramide Égypte:", "tombe pharaon", ["stade", "école", "hôpital"], "Pyramids."),
    ("Gothique: arcs", "brisés", ["plats", "carrés", "triangles"], "Gothic arches."),
    ("Dôme: couvre espace", "circulaire", ["carré seul", "triangulaire seul", "linéaire"], "Dome."),
    ("Haïti art: peinture", "naïve / paysanne", ["inexistante", "interdite", "nulle"], "Haitian art."),
    ("Poto-Poto: style peinture", "haïtien", ["japonais", "scandinave", "arctique"], "Haitian style."),
    ("Jacmel: ville connue pour", "carnaval et artisanat", ["pétrole", "charbon", "uranium"], "Jacmel culture."),
    ("Art haïtien métal: fer", "battu", ["plastique", "papier", "verre seul"], "Metal art."),
    ("Vodou art inclut", "drapo (flags)", ["voitures", "avions", "bateaux"], "Vodou flags."),
    ("Musée d'Art haïtien:", "Port-au-Prince", ["Tokyo", "Paris", "Londres"], "Haiti museum."),
    ("Patrimoine UNESCO Haïti:", "Citadelle, Sans-Souci", ["Tour Eiffel", "Big Ben", "Colisée"], "UNESCO Haiti."),
    ("Design: ergonomie =", "confort d'usage", ["odeur", "taste", "son"], "Ergonomics."),
    ("Typographie: choix de", "police", ["couleur seule", "odeur", "taste"], "Typography."),
    ("Logo identifie une", "marque", ["montagne", "rivière", "nuage"], "Logo."),
    ("Affiche (poster) informe ou", "persuade", ["dort", "mange", "nage"], "Poster."),
    ("CMYK pour", "impression", ["web seul", "radio", "TV"], "Print colors."),
    ("RGB pour", "écran numérique", ["impression seule", "sculpture", "taille"], "Screen colors."),
    ("Pixel =", "point image numérique", ["ligne", "surface", "volume"], "Pixel."),
    ("Résolution =", "densité pixels", ["odeur", "taste", "son"], "Resolution."),
    ("Vectoriel (SVG) vs", "bitmap", ["odeur", "taste", "son"], "Vector vs raster."),
    ("Logiciel dessin: Adobe", "Illustrator", ["Excel", "Word seul", "PowerPoint seul"], "Illustrator."),
    ("Photoshop édite", "images", ["vidéo seule", "audio seul", "texte seul"], "Photoshop."),
    ("Couleur web hex #FF0000 =", "rouge", ["bleu", "vert", "jaune"], "Red hex."),
    ("Art therapy utilise", "création pour bien-être", ["destruction", "censure", "guerre"], "Art therapy."),
    ("Critique d'art analyse", "œuvre et contexte", ["odeur", "taste", "son"], "Art criticism."),
    ("Curateur organise", "exposition", ["cuisine", "sport", "médecine"], "Curator."),
    ("Galerie expose", "œuvres", ["nourriture", "voitures", "bateaux"], "Gallery."),
    ("Musée conserve et", "expose patrimoine", ["détruit", "vend", "brûle"], "Museum."),
    ("Restauration d'œuvre:", "réparer/conservér", ["détruire", "vendre", "brûler"], "Restoration."),
    ("Contemporain = art", "récent / actuel", ["ancien seul", "préhistorique", "interdit"], "Contemporary."),
    ("Performance art =", "action live", ["peinture seule", "sculpture seule", "photo seule"], "Performance."),
    ("Installation art occupe", "espace", ["odeur", "taste", "son seul"], "Installation."),
    ("Land art utilise", "nature/environnement", ["bureau", "classe", "voiture"], "Land art."),
    ("Photographie inventée", "XIXe siècle", ["XIe", "XXIe", "VIIIe"], "Photography history."),
    ("Caméra obscura précède", "appareil photo", ["téléphone", "radio", "TV"], "Camera obscura."),
    ("Noir et blanc =", "monochrome", ["polychrome", "arc-en-ciel", "néon"], "B&W."),
    ("Contraste luminosité =", "clair vs foncé", ["odeur", "taste", "son"], "Tonal contrast."),
    ("Cadrage serré =", "gros plan", ["panorama", "vue satellite", "vue galaxie"], "Close-up."),
    ("Symbole paix:", "colombe / olive", ["épée", "bombe", "fusil"], "Peace symbol."),
    ("Symbole amour:", "cœur", ["carré", "triangle", "hexagone"], "Heart."),
    ("Art haïtien: scène", "quotidienne", ["lunaire", "martienne", "solaire"], "Daily life."),
    ("Art éducatif en 9e AF vise", "expression et culture", ["guerre", "censure", "dictature"], "9e art ed."),
    ("Couleur locale =", "couleur propre objet", ["odeur", "taste", "son"], "Local color."),
    ("Couleur non-locale =", "couleur expressive", ["odeur", "taste", "son"], "Non-local color."),
    ("Matériau recyclé en art =", "art écologique", ["pollution", "déchets toxiques", "brûlage"], "Eco art."),
    ("Artisan =", "créateur manuel", ["robot", "machine seule", "IA seule"], "Artisan."),
    ("Métier d'art =", "savoir-faire traditionnel", ["odeur", "taste", "son"], "Craft."),
    ("Education esthétique =", "sensibilité artistique", ["calcul seul", "sport seul", "guerre"], "Aesthetic ed."),
    ("Education artistique 9e AF inclut", "arts plastiques", ["pétrole", "charbon", "uranium"], "Plastic arts."),
    ("Dessin observé =", "représenter réel", ["ignorer réel", "cacher", "effacer"], "Observational drawing."),
    ("Ombrage crée illusion de", "volume", ["odeur", "taste", "son"], "Shading."),
    ("Pointillisme: Seurat utilise", "points", ["lignes seules", "carrés seuls", "triangles seuls"], "Pointillism."),
    ("Art optique (Op art) joue sur", "illusion", ["odeur", "taste", "son"], "Op art."),
    ("Minimalisme =", "simplicité extrême", ["complexité max", "chaos", "désordre"], "Minimalism."),
    ("Baroque =", "riche et dramatique", ["simple", "minimal", "vide"], "Baroque."),
    ("Renaissance =", "rebirth arts Europe", ["chute", "fin", "destruction"], "Renaissance."),
    ("Michel-Ange sculpte", "David", ["Tour Eiffel", "Big Ben", "Colisée"], "Michelangelo."),
    ("Leonardo da Vinci peint", "Mona Lisa", ["Guernica seule", "Nuit étoilée seule", "Impression soleil"], "Da Vinci."),
    ("Guernica: Picasso proteste", "guerre", ["sport", "musique", "cuisine"], "Guernica."),
    ("Van Gogh: Nuit", "étoilée", ["Jour clair", "Midi", "Aube"], "Starry Night."),
    ("Art africain influence", "modernité occidentale", ["rien", "océan", "lune"], "African art."),
    ("Masque africain utilisé en", "rituel / cérémonie", ["supermarché", "banque", "usine"], "African mask."),
    ("Totem amérindien =", "symbole clan", ["odeur", "taste", "son"], "Totem."),
    ("Art islamique évite souvent", "figures humaines", ["couleurs", "formes", "lignes"], "Islamic art."),
    ("Calligraphie =", "art de l'écriture", ["odeur", "taste", "son"], "Calligraphy."),
    ("Mandala =", "forme circulaire symbolique", ["carré", "triangle", "ligne"], "Mandala."),
    ("Origami =", "papier plié", ["pierre", "métal", "bois"], "Origami."),
    ("Céramique =", "argile cuite", ["papier", "plastique", "air"], "Ceramics."),
    ("Poterie haïtienne:", "terre cuite", ["verre", "métal", "plastique"], "Haitian pottery."),
    ("Tissage =", "entrelacer fils", ["couper", "brûler", "dissoudre"], "Weaving."),
    ("Broderie =", "décorer avec fil", ["odeur", "taste", "son"], "Embroidery."),
    ("Teinture batik utilise", "cire et colorant", ["odeur", "taste", "son"], "Batik."),
    ("Art numérique créé avec", "ordinateur", ["pierre seule", "bois seul", "air"], "Digital art."),
    ("NFT peut certifier", "œuvre numérique", ["odeur", "taste", "son"], "NFT art."),
    ("Animation =", "images en séquence", ["image fixe seule", "odeur", "taste"], "Animation."),
    ("Storyboard planifie", "film/animation", ["cuisine", "sport", "médecine"], "Storyboard."),
    ("Mise en page (layout) organise", "éléments visuels", ["odeur", "taste", "son"], "Layout."),
    ("Contraste de taille guide", "attention", ["odeur", "taste", "son"], "Size contrast."),
    ("Palette limitée =", "peu de couleurs", ["toutes couleurs", "aucune", "infinies"], "Limited palette."),
    ("Art abstrait géométrique: Mondrian utilise", "lignes et couleurs pures", ["photos", "odeurs", "sons"], "Mondrian."),
    ("Kandinsky associe couleur et", "musique", ["odeur", "taste", "poids"], "Kandinsky."),
    ("Art haïtien: marché peint par", "artistes populaires", ["robots", "machines", "nuages"], "Market scenes."),
    ("Fête du drapeau Haïti 18", "mai", ["janvier", "juillet", "décembre"], "Flag day."),
    ("Couleurs drapeau Haïti:", "bleu et rouge", ["vert jaune", "noir seul", "blanc seul"], "Flag colors."),
    ("Art civique éduque à", "citoyenneté", ["guerre", "censure", "dictature"], "Civic art."),
    ("Affiche santé publique =", "communication visuelle", ["odeur", "taste", "son"], "Public health poster."),
    ("Pictogramme =", "symbole universel", ["texte long", "roman", "poème"], "Pictogram."),
    ("Signalétique guide dans", "espace public", ["rêve", "nuage", "lune"], "Signage."),
    ("Couleur sécurité urgence:", "rouge", ["vert pastel", "rose", "beige"], "Emergency red."),
    ("Couleur sécurité sécurité/info:", "vert ou bleu", ["noir", "marron", "beige"], "Safety colors."),
    ("Art inclusif accessible à", "tous", ["riches seuls", "adultes seuls", "hommes seuls"], "Inclusive art."),
    ("Art participatif invite", "public à créer", ["interdit", "censure", "guerre"], "Participatory art."),
    ("Critère esthétique:", "beauté / harmonie", ["odeur", "taste", "poids"], "Aesthetic."),
    ("Critère expressif:", "émotion transmise", ["odeur", "taste", "poids"], "Expressive."),
    ("Critère technique:", "maîtrise matériau", ["odeur", "taste", "poids"], "Technical."),
    ("Portfolio rassemble", "œuvres artiste", ["odeurs", "tastes", "sons"], "Portfolio."),
    ("Exposition temporaire dure", "période limitée", ["éternité", "jamais", "0 seconde"], "Temporary exhibit."),
    ("Collection permanente reste", "longtemps", ["1 seconde", "0 jour", "jamais change"], "Permanent collection."),
    ("Art rupestre = peintures sur", "roche / grottes", ["papier", "écran", "nuage"], "Rock art."),
    ("Préhistoire art: Venus de", "Willendorf", ["Paris", "Tokyo", "Miami"], "Prehistoric."),
    ("Égypte ancienne art pour", "au-delà / pharaons", ["sport", "jeu", "musique seule"], "Egyptian art."),
    ("Grèce: statue Discobole =", "lanceur de disque", ["coureur", "nageur", "skieur"], "Discobolus."),
    ("Rome copie et diffuse art", "grec", ["inuit", "arctique", "lunaire"], "Roman art."),
    ("Byzance: mosaïques en", "or et couleur", ["odeur", "taste", "son"], "Byzantine."),
    ("Roman roman (Romanesque) =", "époque médiévale", ["futur", "préhistoire", "lune"], "Romanesque."),
    ("Art roman arcs", "en plein cintre", ["brisés seuls", "triangulaires", "carrés"], "Rounded arches."),
    ("Art haïtien contemporain exposé", "internationalement", ["jamais", "interdit", "nul"], "Global Haiti art."),
    ("Festival art Jacmel:", "Festival arts", ["Festival pétrole", "Festival charbon", "Festival uranium"], "Jacmel festival."),
    ("Couleur terre (ocre) vient de", "minéraux/pigments naturels", ["odeur", "taste", "son"], "Earth pigments."),
    ("Bleu ultramar vient historiquement de", "lapis lazuli", ["plastique", "papier", "air"], "Ultramarine."),
    ("Vert malachite pigment", "minéral", ["odeur", "taste", "son"], "Malachite."),
    ("Encre sepia couleur", "brune", ["bleue", "verte", "violette"], "Sepia."),
    ("Gris neutre =", "mélange complémentaires", ["eau pure", "air pur", "vide"], "Neutral gray."),
    ("Blanc symbolise souvent", "pureté / lumière", ["guerre", "chaos", "destruction"], "White symbolism."),
    ("Noir symbolise souvent", "mystère / deuil", ["joie seule", "fête seule", "sport"], "Black symbolism."),
    ("Rouge symbolise souvent", "passion / danger", ["calme seul", "silence", "neige"], "Red symbolism."),
    ("Bleu symbolise souvent", "calme / mer", ["feu", "guerre", "chaos"], "Blue symbolism."),
    ("Jaune symbolise souvent", "lumière / joie", ["deuil", "nuit", "silence"], "Yellow symbolism."),
    ("Vert symbolise souvent", "nature / vie", ["pollution", "désert", "glace"], "Green symbolism."),
    ("Art 9e AF: évaluer création selon", "critères donnés", ["hasard", "odeur", "taste"], "9e evaluation."),
    ("Respect matériaux =", "propreté et sécurité", ["désordre", "danger", "pollution"], "Material safety."),
    ("Ciseaux art: ne pas couper vers", "soi", ["autre", "ciel", "sol"], "Scissors safety."),
    ("Colle art: utiliser dans", "zone ventilée", ["fermée sans air", "sous eau", "sous terre"], "Glue safety."),
    ("Peinture: protéger surface avec", "journal / couverture", ["rien", "eau", "sable"], "Paint protection."),
    ("Nettoyer pinceaux à l'", "eau ou solvant adapté", ["sable", "terre", "roche"], "Brush cleaning."),
    ("Chevalet supporte", "toile", ["voiture", "bateau", "avion"], "Easel."),
    ("Palette pour", "mélanger couleurs", ["odeurs", "tastes", "sons"], "Palette."),
    ("Toile peinte =", "support textile", ["métal", "verre", "air"], "Canvas."),
    ("Papier grainé pour", "pastel/charbon", ["eau", "huile seule", "acrylique seule"], "Textured paper."),
    ("Carnet de croquis pour", "esquisses rapides", ["roman", "poème long", "thèse"], "Sketchbook."),
    ("Projet art: moodboard rassemble", "inspirations visuelles", ["odeurs", "tastes", "sons"], "Moodboard."),
    ("Art collaboratif = plusieurs", "artistes ensemble", ["un seul toujours", "aucun", "robot seul"], "Collaborative."),
    ("Art haïtien: perles sur", "bouteilles (vodou)", ["voitures", "avions", "bateaux"], "Bottle art."),
    ("Art haïtien: fer découpé à", "Croix-des-Bouquets", ["Tokyo", "Paris", "Londres"], "Metal village."),
    ("Art mural = peinture sur", "mur", ["sol seul", "ciel", "lune"], "Mural."),
    ("Graffiti sans permission peut être", "illégal", ["toujours légal", "obligatoire", "interdit partout"], "Graffiti law."),
    ("Art public enrichit", "espace commun", ["pollue seul", "détruit seul", "cache"], "Public art."),
    ("Monument commémore", "personne/événement", ["odeur", "taste", "son"], "Monument."),
    ("Statue Liberté symbole", "liberté (USA)", ["guerre", "dictature", "censure"], "Liberty."),
    ("Art révolutionnaire Haïti 1804 inspire", "liberté", ["colonialisme", "esclavage", "dictature"], "Revolution art."),
    ("Affiche politique persuade par", "image et texte", ["odeur", "taste", "son seul"], "Political poster."),
    ("Caricature exagère pour", "critiquer / humoriser", ["odeur", "taste", "son"], "Caricature."),
    ("Bande dessinée combine", "images et texte", ["odeur", "taste", "son seul"], "Comics."),
    ("Manga = BD", "japonaise", ["française", "haïtienne seule", "arctique"], "Manga."),
    ("Animation Disney débute avec", "Mickey Mouse", ["Batman", "Superman", "Spiderman"], "Disney."),
    ("Pixar révolutionne", "animation 3D", ["radio", "journal", "livre seul"], "Pixar."),
    ("Art game design combine", "art et interactivité", ["odeur", "taste", "son seul"], "Game art."),
    ("UI design = interface", "utilisateur", ["backend", "database", "kernel"], "UI design."),
    ("Couleur UI: contraste améliore", "lisibilité", ["odeur", "taste", "son"], "UI contrast."),
    ("Icon set = ensemble d'", "icônes", ["odeurs", "tastes", "sons"], "Icons."),
    ("Art 9e: finalité = expression", "personnelle et culturelle", ["guerre", "censure", "dictature"], "9e purpose."),
]

INFO = [
    ("CPU =", "processeur", ["écran", "clavier", "souris"], "Central Processing Unit."),
    ("RAM =", "mémoire volatile", ["stockage permanent", "écran", "clavier"], "Random Access Memory."),
    ("ROM =", "mémoire permanente", ["volatile", "écran", "clavier"], "Read Only Memory."),
    ("Disque dur (HDD) stocke", "données long terme", ["temporaire seul", "odeur", "taste"], "Storage."),
    ("SSD plus rapide que", "HDD", ["papier", "pierre", "bois"], "Solid State Drive."),
    ("USB connecte", "périphériques", ["nuages", "montagnes", "rivières"], "Universal Serial Bus."),
    ("OS = système", "d'exploitation", ["application seule", "jeu seul", "film"], "Operating System."),
    ("Windows OS de", "Microsoft", ["Apple seul", "Google seul", "Amazon seul"], "Windows."),
    ("macOS OS d'", "Apple", ["Microsoft", "Google", "Linux seul"], "macOS."),
    ("Linux est", "open source", ["fermé secret", "interdit", "payant seul"], "Linux."),
    ("Android OS", "mobile Google", ["desktop seul", "serveur seul", "lune"], "Android."),
    ("iOS sur", "iPhone/iPad", ["Android", "Windows phone", "Symbian"], "iOS."),
    ("Application = logiciel pour", "tâche spécifique", ["odeur", "taste", "son"], "App."),
    ("Navigateur web: Chrome, Firefox,", "Edge", ["Excel", "Word", "PowerPoint"], "Browser."),
    ("URL = adresse", "web", ["postale", "rêve", "nuage"], "Uniform Resource Locator."),
    ("HTTP = protocole", "web", ["email seul", "radio", "TV"], "HyperText Transfer Protocol."),
    ("HTTPS = HTTP", "sécurisé", ["non sécurisé", "fermé", "secret"], "Secure HTTP."),
    ("Wi-Fi = réseau", "sans fil local", ["câble seul", "satellite seul", "lune"], "Wireless."),
    ("Bluetooth = connexion", "courte distance", ["satellite", "lune", "mars"], "Bluetooth."),
    ("Email envoie", "messages numériques", ["odeurs", "tastes", "sons physiques"], "Email."),
    ("Spam = email", "indésirable", ["utile", "officiel", "gouvernemental"], "Spam."),
    ("Phishing = hameçonnage", "frauduleux", ["sport", "musique", "danse"], "Phishing."),
    ("Mot de passe fort: long et", "complexe", ["court simple", "123456", "password"], "Strong password."),
    ("Antivirus protège contre", "malware", ["gravité", "magnétisme", "lumière"], "Antivirus."),
    ("Malware = logiciel", "malveillant", ["bénéfique", "sportif", "musical"], "Malware."),
    ("Ransomware =", "rançongiciel", ["cadeau", "bonus", "sport"], "Ransomware."),
    ("Firewall =", "pare-feu", ["porte ouverte", "virus", "spam"], "Firewall."),
    ("Backup =", "sauvegarde", ["suppression", "effacement", "destruction"], "Backup."),
    ("Cloud = stockage", "distant", ["local seul", "papier", "pierre"], "Cloud."),
    ("Google Drive stocke", "fichiers en ligne", ["odeurs", "tastes", "sons"], "Drive."),
    ("Microsoft Word = traitement de", "texte", ["image seule", "vidéo seule", "audio seule"], "Word."),
    ("Excel =", "tableur", ["peinture", "musique", "danse"], "Spreadsheet."),
    ("PowerPoint =", "présentations", ["jeux seuls", "films seuls", "romans"], "Slides."),
    ("Ctrl+S =", "sauvegarder", ["imprimer", "fermer", "supprimer"], "Save shortcut."),
    ("Ctrl+Z =", "annuler", ["sauvegarder", "imprimer", "fermer"], "Undo."),
    ("Ctrl+C =", "copier", ["coller", "couper", "fermer"], "Copy."),
    ("Ctrl+V =", "coller", ["copier", "couper", "fermer"], "Paste."),
    ("Ctrl+X =", "couper", ["copier", "coller", "fermer"], "Cut."),
    ("Périphérique d'entrée:", "clavier", ["écran", "imprimante", "enceinte"], "Input device."),
    ("Périphérique d'entrée:", "souris", ["écran", "imprimante", "enceinte"], "Mouse input."),
    ("Périphérique sortie:", "écran/moniteur", ["clavier", "souris", "micro"], "Output."),
    ("Périphérique sortie:", "imprimante", ["clavier", "souris", "micro"], "Printer."),
    ("Pixel =", "point d'image", ["ligne", "volume", "odeur"], "Pixel."),
    ("Résolution 1920×1080 =", "Full HD", ["audio", "texte", "odeur"], "1080p."),
    ("Binaire utilise", "0 et 1", ["2 et 3", "A et B", "X et Y"], "Binary."),
    ("Bit =", "0 ou 1", ["octet", "kilobyte", "megabyte"], "Bit."),
    ("Octet (byte) =", "8 bits", ["1 bit", "4 bits", "16 bits"], "Byte."),
    ("KB =", "kilobyte", ["kilobit seul", "megabyte", "gigabyte"], "Kilobyte."),
    ("MB =", "mégabyte", ["kilobyte", "gigabyte", "terabyte"], "Megabyte."),
    ("GB =", "gigabyte", ["megabyte", "kilobyte", "bit"], "Gigabyte."),
    ("Algorithm = suite d'", "instructions", ["rêves", "nuages", "vents"], "Algorithm."),
    ("Programme = code", "exécutable", ["odeur", "taste", "son"], "Program."),
    ("Langage Python utilisé pour", "programmation", ["cuisine", "sport", "danse"], "Python."),
    ("HTML structure", "page web", ["database", "kernel", "driver"], "HTML."),
    ("CSS style", "page web", ["database", "kernel", "driver"], "CSS."),
    ("JavaScript rend page", "interactive", ["statique", "odeur", "taste"], "JavaScript."),
    ("Database stocke", "données structurées", ["odeurs", "tastes", "sons"], "Database."),
    ("SQL interroge", "base de données", ["image", "vidéo", "audio"], "SQL."),
    ("IA = intelligence", "artificielle", ["naturelle humaine", "odeur", "taste"], "AI."),
    ("Machine learning apprend de", "données", ["rien", "rêves", "nuages"], "ML."),
    ("Robot industriel automatise", "usine", ["théâtre", "poésie", "danse"], "Industrial robot."),
    ("Capteur mesure", "données environnement", ["odeur humaine", "taste", "rêve"], "Sensor."),
    ("GPS localise via", "satellites", ["odeur", "taste", "son"], "GPS."),
    ("IoT = internet des", "objets", ["rêves", "nuages", "montagnes"], "IoT."),
    ("5G = réseau mobile", "rapide", ["ancien", "interdit", "nul"], "5G."),
    ("QR code stocke", "info numérique", ["odeur", "taste", "son"], "QR code."),
    ("Technologie 9e AF: éducation à la", "technologie", ["guerre", "censure", "dictature"], "Tech ed."),
    ("Agriculture: semis =", "planter graines", ["récolter", "manger", "dormir"], "Sowing."),
    ("Agriculture: récolte =", "cueillir production", ["planter", "dormir", "manger"], "Harvest."),
    ("Irrigation apporte", "eau aux cultures", ["sable", "roche", "métal"], "Irrigation."),
    ("Engrais enrichit", "sol", ["air", "eau seule", "lumière seule"], "Fertilizer."),
    ("Pesticide combat", "insectes nuisibles", ["plantes", "eau", "air"], "Pesticide."),
    ("Rotation cultures évite", "épuisement sol", ["pollution", "guerre", "censure"], "Crop rotation."),
    ("Serre protège cultures et", "contrôle climat", ["odeur", "taste", "son"], "Greenhouse."),
    ("Tracteur = machine", "agricole", ["médicale", "musicale", "sportive"], "Tractor."),
    ("Moissonneuse récolte", "céréales", ["eau", "air", "lumière"], "Harvester."),
    ("Élevage = production", "animaux", ["rochers", "nuages", "montagnes"], "Livestock."),
    ("Vétérinaire soigne", "animaux", ["plantes", "rochers", "nuages"], "Veterinarian."),
    ("Transformation lait →", "fromage/yogurt", ["pierre", "métal", "bois"], "Dairy processing."),
    ("Conservation aliments: réfrigération", "ralentit bactéries", ["accélère", "ignore", "célèbre"], "Refrigeration."),
    ("Séchage conserve par", "réduction eau", ["ajout eau", "pollution", "guerre"], "Drying."),
    ("Mécanique: levier multiplie", "force", ["odeur", "taste", "son"], "Lever."),
    ("Poulie change direction", "force", ["odeur", "taste", "son"], "Pulley."),
    ("Engrenage transmet", "mouvement", ["odeur", "taste", "son"], "Gear."),
    ("Moteur convertit énergie en", "mouvement", ["odeur", "taste", "son"], "Engine."),
    ("Électricité: générateur produit", "courant", ["odeur", "taste", "son"], "Generator."),
    ("Panneau solaire convertit", "lumière en électricité", ["odeur", "taste", "son"], "Solar panel."),
    ("Éolienne utilise", "vent", ["odeur", "taste", "gravité"], "Wind turbine."),
    ("Circuit électrique besoin", "source, fil, charge", ["odeur", "taste", "son"], "Circuit."),
    ("Ampère mesure", "courant", ["voltage", "résistance", "odeur"], "Ampere."),
    ("Volt mesure", "voltage", ["courant", "résistance", "odeur"], "Volt."),
    ("Sécurité électrique: ne pas toucher", "fil exposé", ["livre", "stylo", "crayon"], "Electrical safety."),
    ("Électronique: résistance limite", "courant", ["odeur", "taste", "son"], "Resistor."),
    ("LED = diode", "électroluminescente", ["odeur", "taste", "son"], "LED."),
    ("Imprimante 3D crée objets en", "couches", ["odeur", "taste", "son"], "3D printing."),
    ("Robot programmé suit", "instructions", ["rêves", "nuages", "vents"], "Robot programming."),
    ("Automatisation réduit travail", "manuel répétitif", ["créatif seul", "artistique seul", "poétique"], "Automation."),
    ("Capteur température mesure", "chaleur", ["odeur", "taste", "couleur"], "Temp sensor."),
    ("Thermostat régule", "température", ["odeur", "taste", "couleur"], "Thermostat."),
    ("Domotique = maison", "connectée", ["odeur", "taste", "son seul"], "Smart home."),
    ("Cybersécurité protège", "données et systèmes", ["odeurs", "tastes", "sons"], "Cybersecurity."),
    ("Encryption =", "chiffrement", ["déchiffrement public", "odeur", "taste"], "Encryption."),
    ("Authentification vérifie", "identité", ["odeur", "taste", "couleur"], "Authentication."),
    ("2FA = deux facteurs", "authentification", ["zéro facteur", "odeur", "taste"], "Two-factor."),
    ("Réseau LAN = réseau", "local", ["global seul", "lunaire", "martien"], "LAN."),
    ("WAN = réseau", "étendu", ["local seul", "personnel seul", "odeur"], "WAN."),
    ("Routeur dirige", "trafic réseau", ["odeur", "taste", "son"], "Router."),
    ("Modem connecte à", "internet", ["lune", "mars", "soleil"], "Modem."),
    ("Serveur fournit", "services/données", ["odeur", "taste", "son"], "Server."),
    ("Client demande", "service serveur", ["odeur", "taste", "son"], "Client."),
    ("Cloud computing = calcul", "distant", ["local seul", "papier", "pierre"], "Cloud computing."),
    ("Open data = données", "ouvertes", ["secrètes", "fermées", "interdites"], "Open data."),
    ("GPS agriculture =", "agriculture de précision", ["odeur", "taste", "son"], "Precision ag."),
    ("Drone agriculture surveille", "cultures", ["océan", "lune", "mars"], "Ag drone."),
    ("Biotechnologie modifie", "organismes vivants", ["rochers", "nuages", "montagnes"], "Biotech."),
    ("OGM = organisme", "génétiquement modifié", ["naturel seul", "roche", "métal"], "GMO."),
    ("Nanotechnologie manipule", "échelle nanométrique", ["kilométrique", "odeur", "taste"], "Nanotech."),
    ("Énergie renouvelable:", "solaire, éolien", ["charbon seul", "pétrole seul", "uranium seul"], "Renewable."),
    ("Recyclage transforme déchets en", "nouveaux produits", ["pollution", "guerre", "censure"], "Recycling."),
    ("E-waste = déchets", "électroniques", ["organiques seuls", "odeurs", "tastes"], "E-waste."),
    ("Durabilité = développement", "durable", ["pollution", "guerre", "censure"], "Sustainability."),
    ("Innovation = nouvelle", "solution", ["copie", "censure", "guerre"], "Innovation."),
    ("Prototypage teste", "concept", ["odeur", "taste", "son"], "Prototyping."),
    ("Design thinking résout problèmes par", "empathie et test", ["guerre", "censure", "dictature"], "Design thinking."),
    ("STEM = Science Technology Engineering", "Math", ["Art seul", "Sport seul", "Musique seul"], "STEM."),
    ("STEAM ajoute", "Art", ["Sport", "Guerre", "Censure"], "STEAM."),
    ("Métrologie = science des", "mesures", ["odeurs", "tastes", "sons"], "Metrology."),
    ("Calibrer outil =", "ajuster précision", ["odeur", "taste", "son"], "Calibrate."),
    ("Qualité contrôle vérifie", "conformité", ["odeur", "taste", "son"], "QC."),
    ("Maintenance préventive évite", "pannes", ["casse", "guerre", "censure"], "Preventive maint."),
    ("Manuel technique guide", "réparation/usage", ["odeur", "taste", "son"], "Technical manual."),
    ("Schéma électrique montre", "circuits", ["odeurs", "tastes", "sons"], "Circuit diagram."),
    ("Plomberie transporte", "eau", ["air seul", "lumière", "son"], "Plumbing."),
    ("Chariot élévateur déplace", "charges lourdes", ["nuages", "montagnes", "rivières"], "Forklift."),
    ("Sécurité atelier: lunettes protègent", "yeux", ["oreilles", "pieds", "cheveux"], "Safety glasses."),
    ("Gants protègent", "mains", ["yeux", "oreilles", "pieds"], "Gloves."),
    ("Signal danger: couleur", "jaune/noir", ["rose", "bleu pastel", "beige"], "Warning colors."),
    ("Éteindre outil avant", "maintenance", ["pendant", "sans arrêt", "en courant"], "Tool safety."),
    ("Technologie haïtienne: EDH fournit", "électricité", ["eau seule", "internet seul", "nourriture"], "EDH."),
    ("Digicel/Natcom =", "télécommunications", ["agriculture", "pêche", "foresterie"], "Telecom Haiti."),
    ("Mobile money = paiement", "mobile", ["papier seul", "pierre", "bois"], "Mobile payment."),
    ("E-learning = apprentissage", "en ligne", ["papier seul", "pierre", "bois"], "E-learning."),
    ("OU TOU BON = plateforme", "éducative numérique", ["restaurant", "hôtel", "banque"], "OU TOU BON."),
    ("Quiz en ligne nécessite", "internet", ["odeur", "taste", "son seul"], "Online quiz."),
    ("PDF partage", "documents", ["odeurs", "tastes", "sons"], "PDF."),
    ("Compression réduit", "taille fichier", ["odeur", "taste", "son"], "Compression."),
    ("ZIP archive", "fichiers", ["odeurs", "tastes", "sons"], "ZIP."),
    ("Versioning garde", "historique modifications", ["odeur", "taste", "son"], "Version control."),
    ("Git versionne", "code", ["odeur", "taste", "son"], "Git."),
    ("GitHub héberge", "repositories", ["restaurants", "hôtels", "musées"], "GitHub."),
    ("API permet apps", "communiquer", ["odeur", "taste", "son"], "API."),
    ("JSON format", "données texte", ["image seule", "vidéo seule", "audio seule"], "JSON."),
    ("Bug = erreur", "logiciel", ["feature", "cadeau", "bonus"], "Bug."),
    ("Debug =", "corriger erreurs", ["créer erreurs", "ignorer", "célébrer"], "Debug."),
    ("Test logiciel vérifie", "fonctionnement", ["odeur", "taste", "son"], "Software test."),
    ("UX design améliore", "expérience utilisateur", ["odeur", "taste", "son"], "UX."),
    ("Accessibilité numérique aide", "tous utilisateurs", ["riches seuls", "adultes seuls", "hommes seuls"], "Digital a11y."),
    ("Écran tactile détecte", "contact", ["odeur", "taste", "gravité"], "Touchscreen."),
    ("Microphone capte", "son", ["lumière", "odeur", "taste"], "Microphone."),
    ("Webcam capture", "vidéo", ["odeur", "taste", "gravité"], "Webcam."),
    ("Enceinte produit", "son", ["lumière", "odeur", "taste"], "Speaker."),
    ("Projecteur affiche sur", "grand écran", ["odeur", "taste", "gravité"], "Projector."),
    ("Tableau interactif =", "écran tactile grand", ["papier", "pierre", "bois"], "Interactive board."),
    ("Robot éducatif apprend", "programmation", ["odeur", "taste", "son"], "Educational robot."),
    ("Arduino = carte", "microcontrôleur", ["odeur", "taste", "son"], "Arduino."),
    ("Capteur ultrason mesure", "distance", ["odeur", "taste", "couleur"], "Ultrasonic."),
    ("LED clignote avec", "programme", ["odeur", "taste", "gravité"], "Blink LED."),
    ("Boucle (loop) répète", "instructions", ["odeur", "taste", "son"], "Loop."),
    ("Condition if/else =", "choix", ["odeur", "taste", "son"], "Conditional."),
    ("Variable stocke", "valeur", ["odeur", "taste", "son"], "Variable."),
    ("Fonction regroupe", "code réutilisable", ["odeur", "taste", "son"], "Function."),
    ("Technologie durable réduit", "impact environnement", ["pollution", "guerre", "censure"], "Sustainable tech."),
    ("Haïti 9e techno: objectif =", "compétences numériques et techniques", ["guerre", "censure", "dictature"], "9e tech goal."),
    ("Métier futur: data", "scientist", ["pierre", "bois", "sable"], "Data science."),
    ("Métier futur: développeur", "web", ["charretier", "torche", "voilier"], "Web dev."),
    ("Métier futur: technicien", "réseau", ["poète", "danseur", "peintre seul"], "Network tech."),
    ("Entrepreneuriat tech crée", "start-up", ["dictature", "guerre", "censure"], "Tech startup."),
    ("Pitch présente", "idée projet", ["odeur", "taste", "son"], "Pitch."),
    ("Business plan décrit", "modèle économique", ["odeur", "taste", "son"], "Business plan."),
    ("Marketing digital utilise", "réseaux sociaux", ["pierre", "bois", "sable"], "Digital marketing."),
    ("E-commerce vend", "en ligne", ["pierre", "bois", "sable"], "E-commerce."),
    ("Logistique gère", "transport stock", ["odeur", "taste", "son"], "Logistics."),
    ("Supply chain = chaîne", "d'approvisionnement", ["odeur", "taste", "son"], "Supply chain."),
    ("Qualité ISO standards", "internationaux", ["locaux secrets", "odeurs", "tastes"], "ISO."),
    ("Lean production réduit", "gaspillage", ["pollution volontaire", "guerre", "censure"], "Lean."),
    ("Kaizen = amélioration", "continue", ["stagnation", "régression", "chaos"], "Kaizen."),
    ("Six Sigma réduit", "défauts", ["qualité", "excellence", "perfection"], "Six Sigma."),
    ("Robot collaboratif (cobot) travaille avec", "humains", ["seul toujours", "nuages", "montagnes"], "Cobot."),
    ("Exosquelette assiste", "mouvement humain", ["odeur", "taste", "son"], "Exoskeleton."),
    ("VR = réalité", "virtuelle", ["odeur", "taste", "son"], "VR."),
    ("AR = réalité", "augmentée", ["odeur", "taste", "son"], "AR."),
    ("Blockchain enregistre transactions", "décentralisées", ["odeurs", "tastes", "sons"], "Blockchain."),
    ("Crypto-monnaie = actif", "numérique", ["physique", "papier", "bois"], "Crypto."),
    ("Smart contract exécute sur", "blockchain", ["papier", "pierre", "bois"], "Smart contract."),
    ("Big data analyse", "grandes données", ["zéro donnée", "odeur", "taste"], "Big data."),
    ("Data privacy = protection", "données personnelles", ["odeurs", "tastes", "sons"], "Privacy."),
    ("Ethics tech évite", "biais et abus", ["tout usage", "aucune règle", "censure totale"], "Tech ethics."),
    ("Green IT réduit", "empreinte carbone numérique", ["pollution", "guerre", "censure"], "Green IT."),
    ("Edge computing traite près de", "source données", ["lune", "mars", "soleil"], "Edge computing."),
    ("Quantum computing utilise", "qubits", ["bits seuls", "odeurs", "tastes"], "Quantum."),
    ("Bioinformatics analyse", "données biologiques", ["odeurs", "tastes", "sons"], "Bioinformatics."),
    ("Telemedicine soins à", "distance", ["pierre", "bois", "sable"], "Telemedicine."),
    ("Wearable capteur sur", "corps", ["lune", "mars", "soleil"], "Wearable."),
    ("Smartwatch suit", "activité/santé", ["odeur", "taste", "gravité"], "Smartwatch."),
    ("Technologie 9e: sécurité numérique =", "protéger identité", ["partager mots de passe", "cliquer tout", "ignorer"], "Digital safety."),
    ("Technologie 9e: agriculture =", "techniques modernes", ["guerre", "censure", "dictature"], "Ag tech."),
    ("Semence améliorée augmente", "rendement", ["odeur", "taste", "son"], "Improved seed."),
    ("Compost enrichit sol avec", "matière organique", ["métal", "plastique", "verre"], "Compost."),
    ("Agroforestry combine", "arbres et cultures", ["guerre", "censure", "dictature"], "Agroforestry."),
    ("Aquaculture = élevage", "aquatique", ["terrestre seul", "aérien seul", "lunaire"], "Aquaculture."),
    ("Pêche durable évite", "surpêche", ["pêche excessive", "pollution", "guerre"], "Sustainable fishing."),
    ("Transformation manioc →", "cassave", ["pierre", "métal", "bois"], "Cassava."),
    ("Hygiène alimentaire évite", "contamination", ["pollution volontaire", "guerre", "censure"], "Food hygiene."),
    ("HACCP contrôle", "sécurité alimentaire", ["odeur", "taste", "son"], "HACCP."),
    ("Technologie rural: pompe à eau", "solaire", ["lunaire", "martienne", "stellaire"], "Solar pump."),
    ("Briquette écologique remplace", "charbon bois", ["pétrole seul", "uranium", "diamant"], "Eco briquette."),
    ("Filtre eau potable élimine", "pathogènes", ["odeurs seules", "couleurs seules", "sons"], "Water filter."),
    ("Éclairage LED réduit", "consommation", ["augmente toujours", "odeur", "taste"], "LED lighting."),
    ("Batterie stocke", "énergie chimique", ["odeur", "taste", "son"], "Battery."),
    ("Chargeur recharge", "batterie", ["odeur", "taste", "son"], "Charger."),
    ("Multiprise protège avec", "fusible/parafoudre", ["odeur", "taste", "son"], "Power strip."),
    ("Câble ethernet connecte", "réseau filaire", ["odeur", "taste", "son"], "Ethernet."),
    ("HDMI transmet", "vidéo/audio numérique", ["odeur", "taste", "gravité"], "HDMI."),
    ("Port USB-C = connecteur", "réversible", ["odeur", "taste", "son"], "USB-C."),
    ("Technologie 9e examen teste", "compétences pratiques et théoriques", ["odeur", "taste", "son"], "9e exam."),
]


def _from_bank(bank: list, category: str) -> list[dict]:
    return bank_to_questions(bank, category, "moyen")


def _prog_art(rng: random.Random) -> list[dict]:
    colors = ["rouge", "jaune", "bleu", "vert", "orange", "violet", "noir", "blanc"]
    shapes = ["cercle", "carre", "triangle", "rectangle", "ovale", "losange"]
    artists = ["Picasso", "Monet", "Van Gogh", "Da Vinci", "Warhol", "Dalí"]
    out = []
    for a, b in [(colors[i], colors[j]) for i in range(len(colors)) for j in range(len(colors)) if i != j]:
        mix = {
            ("rouge", "jaune"): "orange",
            ("jaune", "rouge"): "orange",
            ("bleu", "jaune"): "vert",
            ("jaune", "bleu"): "vert",
            ("rouge", "bleu"): "violet",
            ("bleu", "rouge"): "violet",
        }.get((a, b), rng.choice(colors))
        q = f"Mélange peinture: {a} + {b} donne"
        wrongs = rng.sample([c for c in colors if c != mix], 3)
        opts, ci = shuffle_wrong_options(mix, wrongs, rng)
        out.append(make_q(q, opts, ci, f"{a}+{b} -> {mix}.", "Couleurs", "facile"))
    for shape in shapes:
        q = f"Forme geometrique avec 4 cotes egaux: quel candidat?"
        correct = "carre" if shape == "carre" else rng.choice([s for s in shapes if s != "carre"])
        if shape == "carre":
            correct = "carre"
            q = "Quelle forme a 4 cotes egaux et 4 angles droits?"
        wrongs = [s for s in shapes if s != correct][:3]
        opts, ci = shuffle_wrong_options(correct, wrongs, rng)
        out.append(make_q(q, opts, ci, f"Reponse: {correct}.", "Formes", "facile"))
    for artist in artists:
        q = f"Artiste celebre: {artist} est associe a"
        styles = {
            "Picasso": "cubisme",
            "Monet": "impressionnisme",
            "Van Gogh": "post-impressionnisme",
            "Da Vinci": "Renaissance",
            "Warhol": "pop art",
            "Dalí": "surrealisme",
        }
        correct = styles[artist]
        wrongs = [s for s in styles.values() if s != correct]
        rng.shuffle(wrongs)
        opts, ci = shuffle_wrong_options(correct, wrongs[:3], rng)
        out.append(make_q(q, opts, ci, f"{artist}: {correct}.", "Histoire art", "moyen"))
    for i in range(80):
        n = rng.randint(2, 10)
        q = f"Art: un carre de cote {n} cm a une aire de"
        correct = f"{n * n} cm2"
        wrongs = [f"{n * 2} cm2", f"{n + n} cm2", f"{n * 3} cm2"]
        opts, ci = shuffle_wrong_options(correct, wrongs, rng)
        out.append(make_q(q, opts, ci, f"Aire = {n}×{n} = {n*n} cm2.", "Geometrie art", "facile"))
    return out


def _prog_info(rng: random.Random) -> list[dict]:
    out = []
    units = [("bit", "0 ou 1"), ("byte", "8 bits"), ("KB", "1024 bytes"), ("MB", "1024 KB")]
    for u, defn in units:
        q = f"En informatique, {u} correspond a :"
        wrongs = [d for _, d in units if d != defn]
        opts, ci = shuffle_wrong_options(defn, wrongs, rng)
        out.append(make_q(q, opts, ci, f"{u} = {defn}.", "Informatique", "facile"))
    for n in range(2, 33):
        q = f"Convertir {n} GB en MB (x1024):"
        correct = str(n * 1024)
        wrongs = [str(n * 1000), str(n * 512), str(n + 1024)]
        opts, ci = shuffle_wrong_options(correct, wrongs, rng)
        out.append(make_q(q, opts, ci, f"{n} GB = {correct} MB.", "Informatique", "moyen"))
    for n in range(2, 33):
        q = f"Convertir {n} MB en KB (x1024):"
        correct = str(n * 1024)
        wrongs = [str(n * 1000), str(n * 512), str(n + 100)]
        opts, ci = shuffle_wrong_options(correct, wrongs, rng)
        out.append(make_q(q, opts, ci, f"{n} MB = {correct} KB.", "Informatique", "moyen"))
    for bits in range(1, 17):
        q = f"Avec {bits} bits, combien de valeurs distinctes (2^n)?"
        correct = str(2 ** bits)
        wrongs = [str(bits * 2), str(bits + 2), str(bits ** 2)]
        opts, ci = shuffle_wrong_options(correct, wrongs, rng)
        out.append(make_q(q, opts, ci, f"2^{bits} = {correct}.", "Binaire", "moyen"))
    for speed in [64, 128, 256, 512, 1024, 2048, 4096, 8000]:
        q = f"USB {speed} Mbps: vitesse theorique"
        correct = f"{speed} Mbps"
        wrongs = [f"{speed // 2} Mbps", f"{speed * 2} Mbps", f"{speed + 100} Mbps"]
        opts, ci = shuffle_wrong_options(correct, wrongs, rng)
        out.append(make_q(q, opts, ci, f"USB {speed} = {correct}.", "Hardware", "moyen"))
    return out


def generate_art(rng: random.Random, seen: set[str]) -> list[dict]:
    out = _from_bank(ART, "Art plastique") + _prog_art(rng)
    rng.shuffle(out)
    return out


def generate_informatique(rng: random.Random, seen: set[str]) -> list[dict]:
    out = _from_bank(INFO, "Technologie") + _prog_info(rng)
    rng.shuffle(out)
    return out
