"""Histoire / sciences sociales 9e AF — banque locale."""
from __future__ import annotations

import random

from .common import make_q, shuffle_wrong_options

HAITI_DEPTS = [
    ("Artibonite", "Gonaïves"),
    ("Centre", "Hinche"),
    ("Grand'Anse", "Jérémie"),
    ("Nippes", "Miragoâne"),
    ("Nord", "Cap-Haïtien"),
    ("Nord-Est", "Fort-Liberté"),
    ("Nord-Ouest", "Port-de-Paix"),
    ("Ouest", "Port-au-Prince"),
    ("Sud", "Les Cayes"),
    ("Sud-Est", "Jacmel"),
]

PRESIDENTS = [
    ("Alexandre Pétion", "1806-1818"),
    ("Jean-Pierre Boyer", "1818-1843"),
    ("Fabre Geffrard", "1859-1867"),
    ("Ulisses Heureaux", "non haïtien"),
    ("Anténor Firmin", "non président"),
    ("Sténio Vincent", "1930-1941"),
    ("François Duvalier", "1957-1971"),
    ("Jean-Claude Duvalier", "1971-1986"),
    ("René Préval", "1996-2001, 2006-2011"),
    ("Michel Martelly", "2011-2016"),
]

WWII = [
    ("1939", "Début de la Seconde Guerre mondiale"),
    ("1945", "Fin de la Seconde Guerre mondiale"),
    ("Allemagne", "Pays responsable du début du conflit en Europe"),
    ("Axe", "Alliance Allemagne-Italie-Japon"),
    ("Alliés", "France, Royaume-Uni, URSS, USA…"),
    ("Holocauste", "Extermination systématique des Juifs"),
    ("6 millions", "Nombre approximatif de Juifs assassinés"),
]

CARIBBEAN = [
    ("CARICOM", "Organisation régionale des Caraïbes"),
    ("14", "Nombre de pays membres pleins de la CARICOM (approx.)"),
    ("Jamaïque", "Pays anglophone des Grandes Antilles"),
    ("Cuba", "Plus grande île des Caraïbes"),
    ("Barbade", "Petite île indépendante à l'est des Caraïbes"),
]

STATIC = [
    ("Quelle date marque l'indépendance d'Haïti ?", "1804", ["1791", "1825", "1863"], "Haïti proclame son indépendance le 1er janvier 1804."),
    ("Qui fut le premier chef d'État noir indépendant d'Haïti ?", "Jean-Jacques Dessalines", ["Toussaint Louverture", "Henri Christophe", "Alexandre Pétion"], "Dessalines proclame l'indépendance en 1804."),
    ("La Révolution haïtienne débute en :", "1791", ["1776", "1804", "1843"], "Le soulèvement des esclaves commence en 1791 à Saint-Domingue."),
    ("Quel traité reconnaît l'indépendance d'Haïti en 1825 ?", "Accord avec France (indemnité)", ["Traité de Versailles", "Traité de Ghent", "Traité de Paris 1783"], "France exige une indemnité en 1825."),
    ("Capitale d'Haïti :", "Port-au-Prince", ["Cap-Haïtien", "Jacmel", "Les Cayes"], "Port-au-Prince est la capitale administrative."),
    ("Haïti partage l'île d'Hispaniola avec :", "la République dominicaine", ["Cuba", "Jamaïque", "Porto Rico"], "L'île est partagée entre Haïti et la RD."),
    ("La Première Guerre mondiale se déroule entre :", "1914 et 1918", ["1939 et 1945", "1870 et 1871", "1912 et 1916"], "WWI : 1914-1918."),
    ("L'URSS est l'acronyme de :", "Union des Républiques socialistes soviétiques", ["Union des États scandinaves", "Union sud-américaine", "Unité soviétique du Sud"], "URSS = Union soviétique."),
    ("Le mur de Berlin est construit en :", "1961", ["1945", "1989", "1956"], "Le mur divise Berlin de 1961 à 1989."),
    ("La chute du mur de Berlin date de :", "1989", ["1961", "1991", "2001"], "Symbole de la fin de la Guerre froide."),
    ("La Guerre froide oppose principalement :", "USA et URSS", ["France et Allemagne", "Chine et Japon", "Brésil et Argentine"], "Bipolarisation après 1945."),
    ("L'ONU est créée en :", "1945", ["1919", "1955", "1939"], "Organisation des Nations unies après WWII."),
    ("Le siège de l'ONU est à :", "New York", ["Genève", "Paris", "Washington"], "Siège principal à New York."),
    ("La déclaration des droits de l'homme et du citoyen date de :", "1789", ["1776", "1804", "1848"], "Révolution française — 1789."),
    ("Qui écrit « Les Lumières » au XVIIIe siècle ?", "Voltaire, Rousseau, Montesquieu", ["Napoléon seul", "Louis XIV", "Robespierre seul"], "Philosophes des Lumières."),
    ("La Révolution française commence en :", "1789", ["1799", "1815", "1830"], "Prise de la Bastille — 14 juillet 1789."),
    ("Napoléon Bonaparte devient empereur en :", "1804", ["1789", "1815", "1792"], "Empire français — 1804."),
    ("La colonisation européenne des Amériques commence au :", "XVIe siècle", ["XIe siècle", "XXe siècle", "VIIIe siècle"], "Christophe Colomb — 1492."),
    ("1492 : quel explorateur atteint les Amériques pour l'Espagne ?", "Christophe Colomb", ["Vasco de Gama", "Magellan", "Marco Polo"], "Arrivée dans les Caraïbes en 1492."),
    ("Le commerce triangulaire relie :", "Europe, Afrique, Amériques", ["Asie, Europe, Afrique", "USA, Canada, Mexique", "Russie, Chine, Inde"], "Traite atlantique."),
    ("Quel océan borde Haïti au nord ?", "l'Atlantique", ["le Pacifique", "l'Indien", "l'Arctique"], "Haïti est dans l'Atlantique nord."),
    ("Monnaie officielle d'Haïti :", "gourde haïtienne", ["peso", "dollar US", "euro"], "Code ISO : HTG."),
    ("Langues officielles d'Haïti :", "français et créole haïtien", ["anglais et espagnol", "français seul", "espagnol et créole"], "Bilinguisme constitutionnel."),
    ("Le département de l'Ouest inclut :", "Port-au-Prince", ["Cap-Haïtien", "Jérémie", "Hinche"], "Capitale dans l'Ouest."),
    ("Jacmel est dans le département :", "Sud-Est", ["Ouest", "Nord", "Artibonite"], "Ville historique du Sud-Est."),
    ("Les Cayes est chef-lieu du :", "Sud", ["Nord", "Grand'Anse", "Nippes"], "Département du Sud."),
    ("Cap-Haïtien est dans le :", "Nord", ["Ouest", "Sud-Est", "Centre"], "Deuxième ville du pays."),
    ("La Constitution haïtienne actuelle (récente) date de :", "1987", ["1804", "1915", "1957"], "Constitution de 1987, amendée."),
    ("L'indépendance de la RD (partie est) date de :", "1844", ["1804", "1821", "1865"], "Séparation de la partie espagnole."),
    ("Le canal de Panama relie :", "Atlantique et Pacifique", ["Méditerranée et Atlantique", "Indien et Pacifique", "Baltique et Atlantique"], "Passage interocéanique."),
    ("La Grande Dépression commence en :", "1929", ["1914", "1945", "1960"], "Krach boursier — 1929."),
    ("Le New Deal est une politique de :", "Franklin D. Roosevelt", ["Woodrow Wilson", "Harry Truman", "John Kennedy"], "Relance économique USA 1930s."),
    ("La bombe atomique est utilisée en :", "1945", ["1939", "1950", "1918"], "Hiroshima et Nagasaki — 1945."),
    ("La Conférence de Bandung (1955) réunit des pays :", "afro-asiatiques", ["européens", "américains", "scandinaves"], "Mouvement des non-alignés."),
    ("L'apartheid est un régime de ségrégation en :", "Afrique du Sud", ["Kenya", "Égypte", "Nigeria"], "Régime racial jusqu'en 1994."),
    ("Nelson Mandela est emprisonné puis devient :", "président de l'Afrique du Sud", ["premier ministre du Kenya", "roi du Ghana", "général en Égypte"], "Premier président noir post-apartheid."),
    ("La décolonisation africaine s'accélère dans les :", "années 1960", ["années 1850", "années 1990", "années 1750"], "Indépendances massives 1960s."),
    ("Le panafricanisme promeut :", "l'unité et la dignité africaine", ["la colonisation", "l'isolationnisme", "la monarchie absolue"], "Idée d'unité africaine."),
    ("La Shoah cible principalement :", "les Juifs", ["les catholiques", "les bouddhistes", "les hindous"], "Génocide des Juifs par le nazisme."),
    ("Adolf Hitler dirige :", "l'Allemagne nazie", ["l'Italie fasciste", "la France", "l'URSS"], "Troisième Reich — 1933-1945."),
    ("Mussolini est le leader fasciste de :", "l'Italie", ["l'Espagne", "la Grèce", "la Pologne"], "Régime fasciste italien."),
    ("La Révolution industrielle commence en :", "Grande-Britagne", ["Haïti", "Japon", "Brésil"], "XVIIIe siècle — textile, charbon."),
    ("Le suffrage universel masculin en France date approximativement de :", "1848", ["1789", "1918", "1945"], "Deuxième République — 1848."),
    ("La Commune de Paris est en :", "1871", ["1789", "1914", "1968"], "Révolution sociale — 1871."),
    ("Le canal de Suez relie :", "Méditerranée et mer Rouge", ["Atlantique et Pacifique", "Baltique et Atlantique", "Indien et Pacifique"], "Égypte — lien Europe/Asie."),
    ("L'Empire ottoman est dissous après :", "la Première Guerre mondiale", ["la Révolution française", "la Guerre froide", "la WWII"], "Traité de Sèvres / partition."),
    ("Le traité de Versailles (1919) sanctionne :", "l'Allemagne", ["la France", "les USA", "la Russie"], "Paix après WWI."),
    ("La Ligue des Nations précède :", "l'ONU", ["l'OTAN", "la CARICOM", "l'Union européenne"], "Créée en 1919, inefficace."),
    ("L'OTAN est une alliance :", "militaire occidentale", ["économique africaine", "culturelle asiatique", "sportive"], "Organisation atlantique nord."),
    ("Le Plan Marshall aide :", "l'Europe après 1945", ["l'Afrique en 1804", "l'Asie en 1914", "l'Amérique en 1789"], "Reconstruction européenne."),
    ("La crise des missiles de Cuba date de :", "1962", ["1956", "1975", "1989"], "Guerre froide — Kennedy/Khrushchev."),
    ("La guerre du Vietnam se termine en :", "1975", ["1945", "1962", "1991"], "Chute de Saigon — 1975."),
    ("Le 11 septembre 2001 : attentats aux :", "États-Unis", ["France", "Haïti", "Japon"], "Attentats contre le World Trade Center."),
    ("Le Brexit concerne le retrait du :", "Royaume-Uni de l'UE", ["France de l'OTAN", "USA de l'ONU", "Canada de la CARICOM"], "Référendum 2016, sortie 2020."),
    ("La monnaie de l'Union européenne est :", "l'euro", ["le dollar", "la livre", "le yen"], "Euro depuis 1999/2002."),
    ("Haïti est membre de :", "CARICOM", ["OTAN", "Union européenne", "ASEAN"], "Organisation caribéenne."),
    ("Le Morne à l'UNESCO en Haïti commémore :", "le combat pour la liberté", ["la colonisation française", "la WWI", "la WW2"], "Site du Morne — patrimoine."),
    ("Citadelle Laferrière construite par :", "Henri Christophe", ["Dessalines", "Boyer", "Pétion"], "Forteresse du Nord — XIXe."),
    ("Palais Sans-Souci situé à :", "Milot (Nord)", ["Port-au-Prince", "Jacmel", "Les Cayes"], "Résidence de Christophe."),
    ("Code postal haïtien : format", "4 chiffres", ["2 lettres", "6 chiffres", "8 chiffres"], "Système postal national."),
    ("Recensement : objectif principal", "connaître la population", ["fixer les prix", "élire le président", "imprimer l'argent"], "Données démographiques."),
    ("Un référendum permet :", "voter directement sur une question", ["élire un maire", "juger un crime", "nommer un juge"], "Vote populaire direct."),
    ("Séparation des pouvoirs : exécutif, légisif et", "judiciaire", ["militaire", "religieux", "économique"], "Montesquieu — équilibre."),
    ("Démocratie : pouvoir vient du", "peuple", ["roi", "armée", "église seule"], "Souveraineté populaire."),
    ("Dictature : pouvoir concentré chez", "un seul leader", ["tous les citoyens", "les juges", "les maires"], "Absence de contre-pouvoir."),
    ("La carte : légende indique", "les symboles utilisés", ["le prix des produits", "les noms des enfants", "les recettes"], "Lecture cartographique."),
    ("Sur une carte, l'échelle 1/50 000 signifie", "1 cm = 500 m", ["1 cm = 5 m", "1 cm = 50 km", "1 cm = 5 km"], "1/50000 × 100m = 500m."),
    ("Latitude mesure la distance", "nord-sud", ["est-ouest", "verticale du temps", "de la population"], "Parallèles."),
    ("Longitude mesure la distance", "est-ouest", ["nord-sud", "altitude", "densité"], "Méridiens."),
    ("Équateur divise la Terre en", "hémisphères nord et sud", ["est et ouest seuls", "zones urbaines", "continents"], "Ligne 0° latitude."),
    ("Méridien de Greenwich : longitude", "0°", ["90°", "180°", "45°"], "Référence longitude."),
    ("Continent haïtien :", "Amérique du Nord (Caraïbes)", ["Europe", "Afrique", "Asie"], "Archipel des Caraïbes."),
    ("Plus grand département haïtien en superficie :", "Artibonite", ["Ouest", "Nippes", "Nord-Ouest"], "Vallée fertile Artibonite."),
    ("Agriculture haïtienne importante :", "café et mangue", ["pétrole", "charbon", "uranium"], "Produits agricoles d'export."),
    ("Déforestation en Haïti cause souvent", "érosion et inondations", ["plus de neige", "baisse des tempêtes", "augmentation des forêts"], "Impact environnemental."),
    ("Cyclone tropical : saison en Haïti", "juin à novembre", ["janvier à mars", "décembre seul", "toute l'année égale"], "Saison cyclonique atlantique."),
    ("ONU — organe de sécurité :", "Conseil de sécurité", ["Cour de football", "Banque centrale", "Musée"], "5 membres permanents."),
    ("Droits de l'enfant : convention de", "1989", ["1804", "1945", "2000"], "CIDE — 1989."),
    ("Médias : la presse écrite s'appelle souvent", "journal", ["téléphone", "route", "montagne"], "Média imprimé."),
    ("Citoyenneté : droit de vote =", "suffrage", ["taxe", "douane", "monopole"], "Participation politique."),
    ("Immigration : déménager vers", "un autre pays", ["une autre maison", "un autre quartier", "un autre lit"], "Changement de nationalité/résidence."),
    ("Émigration : quitter son pays pour", "vivre ailleurs", ["rester", "ne jamais bouger", "dormir"], "Sortie du territoire."),
    ("Globalisation : intensification des échanges", "mondiaux", ["locaux seuls", "familiaux", "inexistants"], "Interconnexion planétaire."),
    ("FMI : objectif principal", "stabilité financière internationale", ["culture sportive", "cuisine", "mode"], "Fonds monétaire international."),
    ("Banque mondiale aide au", "développement", ["conflit armé", "censure", "dictature"], "Projets de développement."),
    ("Haïti — fête nationale indépendance :", "1er janvier", ["14 juillet", "4 juillet", "25 décembre"], "1804 — Nouvel An."),
    ("Fête du drapeau haïtien :", "18 mai", ["1er janvier", "17 octobre", "2 janvier"], "Adoption du drapeau."),
    ("Couleurs du drapeau haïtien :", "bleu et rouge", ["vert et jaune", "noir seul", "blanc seul"], "Bleu et rouge avec blanc."),
    ("Devise sur le drapeau :", "L'Union fait la Force", ["Liberté, Égalité, Fraternité", "In God We Trust", "E pluribus unum"], "Union fait la force."),
    ("Premier empire haïtien proclamé par :", "Dessalines", ["Pétion", "Boyer", "Geffrard"], "Empire 1804."),
    ("Division Nord/Sud Haïti : région montagneuse", "Massif de la Selle", ["Sahara", "Himalaya", "Alpes"], "Chaîne dominante."),
    ("Pic le plus élevé d'Haïti :", "Pic la Selle", ["Pic Macaya", "Pic du Canigou", "Mont Blanc"], "2680 m approx."),
    ("Golfe de la Gonâve borde l'ouest de :", "Haïti", ["Cuba", "Jamaïque", "Bahamas"], "Entre Haïti et île de la Gonâve."),
    ("Île de la Tortue est au :", "nord-ouest d'Haïti", ["sud-est", "centre", "est de Cuba"], "Département Nord-Ouest."),
    ("Traite des esclaves : « Middle Passage » =", "traversée Atlantique", ["route du café", "route du sucre", "route du coton"], "Passage Atlantique."),
    ("Abolition de la traite (UK) :", "1807", ["1492", "1900", "2000"], "Loi britannique 1807."),
    ("Abolition de l'esclavage en France (1848) par :", "Victor Schoelcher", ["Napoléon", "Louis XIV", "De Gaulle"], "Décret d'abolition."),
    ("Guerre de Sécession américaine :", "1861-1865", ["1776-1783", "1914-1918", "1939-1945"], "USA — Nord vs Sud."),
    ("Abraham Lincoln associe à :", "abolition de l'esclavage (USA)", ["WWI", "WWII", "Révolution française"], "Proclamation d'émancipation."),
    ("Rosa Parks symbole de :", "droits civiques (USA)", ["WWII", "colonisation", "Révolution industrielle"], "Boycott des bus — 1955."),
    ("Martin Luther King défend :", "égalité civique", ["colonialisme", "apartheid positif", "dictature"], "Mouvement non violent."),
    ("Guerre froide : course aux", "armements nucléaires", ["poèmes", "tableaux", "fromages"], "Dissuasion nucléaire."),
    ("Khrushchev dirigeait :", "URSS", ["USA", "France", "UK"], "Dirigeant soviétique."),
    ("Chute de l'URSS :", "1991", ["1961", "1945", "2005"], "Dissolution soviétique."),
    ("Printemps arabe : vague de", "protests et révolutions", ["neige", "sécheresse", "volcan"], "Début 2011 région MENA."),
    ("Printemps des peuples (1848) en Europe :", "révolutions nationales", ["guerre mondiale", "traité de paix", "découverte Amérique"], "Vague révolutionnaire."),
    ("Révolution haïtienne : leader Toussaint", "Louverture", ["Columbus", "Washington", "Lincoln"], "Général de la révolution."),
    ("Henri Christophe se proclame", "roi", ["empereur", "président à vie", "maire"], "Royaume du Nord."),
    ("Code rural haïtien (XIXe) visait à", "contrôler les travailleurs", ["libérer tous", "abolir l'agriculture", "créer l'ONU"], "Réglementation post-indépendance."),
    ("Occupation américaine d'Haïti :", "1915-1934", ["1804-1810", "1957-1986", "2004-2006"], "Intervention US."),
    ("Duvalier — période dictature :", "1957-1986", ["1915-1934", "1804-1820", "1990-2000"], "François et Jean-Claude."),
    ("Earthquake majeur Port-au-Prince :", "2010", ["2004", "2016", "1991"], "12 janvier 2010."),
    ("MINUSTAH : mission", "ONU en Haïti", ["NATO", "CARICOM", "FMI"], "Stabilisation ONU."),
    ("Organisation régionale Caraïbes anglophones :", "CARICOM", ["Mercosur", "ASEAN", "EU"], "Coopération caribéenne."),
    ("OEA concerne :", "Amériques", ["Europe", "Afrique", "Asie"], "Organisation des États américains."),
    ("ALENA / USMCA concerne", "USA, Canada, Mexique", ["Haïti, Cuba, Jamaïque", "France, Allemagne", "Chine, Japon"], "Accord commercial nord-américain."),
    ("Union européenne fondée (traité de Rome) :", "1957", ["1789", "1919", "2001"], "CEE — Rome 1957."),
    ("Berlin conférence 1884 :", "partage de l'Afrique", ["indépendance haïtienne", "WWI", "WWII"], "Colonialisme africain."),
    ("Apartheid commence officiellement vers :", "1948", ["1804", "1914", "1994"], "Régime institutionnel."),
    ("Indépendance Ghana (Nkrumah) :", "1957", ["1844", "1962", "2000"], "Premier pays noir indépendant."),
    ("Indépendance Inde :", "1947", ["1918", "1939", "1960"], "Fin du Raj britannique."),
    ("Révolution cubaine :", "1959", ["1898", "1939", "1989"], "Prise de pouvoir de Castro."),
    ("Guerre d'Espagne (1936-1939) précède :", "WWII", ["WWI", "Guerre froide", "Révolution française"], "Conflit avant WWII."),
    ("Stalin dirige :", "URSS", ["USA", "UK", "France"], "Leader soviétique."),
    ("Churchill dirige :", "UK (WWII)", ["France", "Allemagne", "Italie"], "Premier ministre britannique."),
    ("De Gaulle symbole de :", "France libre (WWII)", ["Allemagne nazie", "URSS", "Japon impérial"], "Résistance française."),
    ("Holocauste : camps d'extermination en", "Pologne et Europe occupée", ["Amérique du Sud", "Australie", "Groenland"], "Camps nazis."),
    ("Nuremberg : procès des", "criminels nazis", ["soldats haïtiens", "rois africains", "explorateurs"], "Tribunaux post-WWII."),
    ("ONU — siège en Europe (agences) :", "Genève, Vienne…", ["Port-au-Prince", "Jacmel", "Les Cayes"], "Agences multilatérales."),
    ("Droit international : tribunal à", "La Haye", ["Miami", "Tokyo", "Sydney"], "Cour internationale."),
    ("Patrimoine mondial UNESCO :", "sites culturels/naturels protégés", ["stades de foot", "malls", "parking"], "Protection patrimoine."),
    ("Démographie : natalité élevée =", "taux de natalité haut", ["mortalité haute", "émigration nulle", "zéro enfants"], "Nombre de naissances."),
    ("Pyramide des âges montre", "structure par âge", ["couleurs du drapeau", "prix du riz", "routes"], "Visualisation population."),
    ("Urbanisation : croissance des", "villes", ["forêts", "déserts", "océans"], "Concentration urbaine."),
    ("Exode rural : départ des campagnes vers", "villes", ["montagnes", "mers", "volcans"], "Migration interne."),
    ("Séisme : plaque tectonique Caraïbes", "risque géologique", ["aucun risque", "glace permanente", "déserts"], "Zone sismique."),
    ("Tsunami causé souvent par", "séisme sous-marin", ["vent léger", "pluie fine", "brouillard"], "Vague gigantesque."),
    ("Climat tropical haïtien :", "chaud et humide", ["polaire", "désertique sec", "glacial"], "Climat tropical."),
    ("Saison des pluies en Haïti :", "printemps-été", ["décembre seul", "aucune pluie", "neige"], "Saison pluvieuse."),
    ("Ressource en eau : barrage important", "Péligre", ["Tour Eiffel", "Big Ben", "Colisée"], "Barrage hydroélectrique."),
    ("Énergie renouvelable :", "solaire, éolien", ["charbon seul", "pétrole seul", "bois seul"], "Alternatives fossiles."),
    ("Pollution : CO₂ contribue au", "changement climatique", ["ralentissement Terre", "augmentation gravité", "plus de lunes"], "Gaz à effet de serre."),
    ("Accord de Paris (climat) :", "2015", ["1804", "1914", "1991"], "COP21 — climat."),
    ("Développement durable : équilibre", "économie, social, environnement", ["guerre, pollution, pauvreté", "dictature", "colonialisme"], "Trois piliers."),
    ("Microcrédit aide les", "petits entrepreneurs", ["multinationales seules", "dictateurs", "armées"], "Finance inclusive."),
    ("ONU — objectif développement :", "ODD 2030", ["ODD 1804", "ODD 1492", "ODD 0000"], "17 objectifs 2030."),
    ("Éducation : droit fondamental selon", "ONU", ["aucune loi", "seulement riches", "seulement urbains"], "Droit à l'éducation."),
    ("Santé publique : vaccination prévient", "maladies", ["routes", "volcans", "tides"], "Immunisation."),
    ("Census vs enquête : recensement couvre", "toute la population", ["10 personnes", "aucune", "seulement enfants"], "Comptage national."),
    ("Carte politique montre", "frontières et États", ["températures", "nuages", "rêves"], "Divisions politiques."),
    ("Carte physique montre", "relief et cours d'eau", ["votes", "prix", "lois"], "Relief naturel."),
    ("Compass rose indique", "nord, sud, est, ouest", ["haut, bas, gauche, droite seules", "couleurs", "sons"], "Orientation."),
    ("Échelle grande (1/10 000) = zone", "détaillée petite", ["planète entière", "galaxie", "univers"], "Grand détail local."),
    ("Haïti — bicaméral : Chambre des députés et", "Sénat", ["Cour suprême seule", "Mairie", "Église"], "Parlement."),
    ("Président haïtien élu pour", "5 ans", ["10 ans", "vie", "1 mois"], "Mandat constitutionnel."),
    ("Premier ministre haïtien : rôle", "chef du gouvernement", ["juge suprême", "maire PAP", "général armée"], "Exécutif gouvernemental."),
    ("Municipalité : élu local =", "maire", ["président monde", "roi", "empereur"], "Administration locale."),
    ("Taxe collectée par l'État =", "impôt", ["cadeau", "don anonyme", "loterie forcée"], "Financement public."),
    ("Budget public finance", "services publics", ["vacances privées", "armes personnelles", "maisons privées"], "Écoles, routes, santé."),
    ("Corruption : usage illégal du", "pouvoir pour gain", ["sport", "art", "musique"], "Abus de fonction."),
    ("Transparence gouvernementale favorise", "confiance citoyenne", ["secret total", "censure", "dictature"], "Gouvernance ouverte."),
    ("Presse libre permet", "informer le public", ["cacher tout", "interdire vote", "annuler lois"], "Liberté d'expression."),
    ("Propagande diffuse des", "idées biaisées", ["faits neutres", "silence", "rien"], "Manipulation opinion."),
    ("Révolution numérique : internet et", "technologies", ["charrettes", "torches", "pierre"], "Société connectée."),
    ("Cybercriminalité : crime via", "réseaux numériques", ["champs", "rivières", "montagnes"], "Hacking, fraude."),
    ("Diplomatie : négociation entre", "États", ["planètes", "animaux seuls", "rochers"], "Relations internationales."),
    ("Ambassade représente un pays", "à l'étranger", ["dans l'espace", "sous l'eau", "sur la lune"], "Mission diplomatique."),
    ("Sanctions internationales punissent", "violation de règles", ["victoires sportives", "fêtes", "musique"], "Mesures économiques."),
    ("Paix : traité signé après", "guerre ou conflit", ["avant tout", "jamais", "seulement sport"], "Accord de paix."),
    ("Genocide défini par l'ONU : destruction intentionnelle d'un", "groupe", ["bâtiment", "route", "nuage"], "Crime international."),
    ("Droits humains : universels et", "indivisibles", ["optionnels", "seulement riches", "seulement hommes"], "DUDH 1948."),
    ("Charte des Nations unies signée en", "1945", ["1789", "1804", "2001"], "Fondation ONU."),
    ("Secours humanitaire : Croix-Rouge aide en", "crises", ["guerre seulement", "fête seulement", "vacances"], "Aide d'urgence."),
    ("Réfugié : personne qui quitte son pays par", "peur ou guerre", ["tourisme", "plaisir", "curiosité"], "Protection internationale."),
    ("Migrant climatique déplacé par", "catastrophes environnementales", ["choix de couleur", "musique", "sport"], "Changement climatique."),
    ("Commerce équitable favorise", "producteurs locaux", ["monopoles", "dumping", "contrebande"], "Prix justes."),
    ("Dumping : vendre à prix", "inférieur au marché", ["double", "triple", "quadruple"], "Pratique commerciale."),
    ("Monopole : un seul vendeur contrôle", "le marché", ["rien", "tout le monde", "aucun produit"], "Absence concurrence."),
    ("Inflation : hausse générale des", "prix", ["arbres", "montagnes", "étoiles"], "Perte valeur monétaire."),
    ("Déflation : baisse générale des", "prix", ["nuages", "sables", "glaces"], "Rare mais possible."),
    ("Banque centrale haïtienne :", "Banque de la République d'Haïti", ["FMI", "Banque mondiale", "CARICOM"], "BRH."),
    ("Exportation : vendre vers", "l'étranger", ["la maison", "le lit", "le rêve"], "Commerce sortant."),
    ("Importation : acheter depuis", "l'étranger", ["le sous-sol", "la lune", "Mars"], "Commerce entrant."),
    ("Balance commerciale : exportations −", "importations", ["population", "température", "nuages"], "Solde commercial."),
    ("SMIC ou salaire minimum protège", "travailleurs", ["multinationales seules", "dictateurs", "armées"], "Salaire de base."),
    ("Syndicat défend les", "droits des travailleurs", ["entreprises seules", "gouvernements seuls", "rois"], "Organisation labor."),
    ("Grève : arrêt de travail pour", "négocier", ["dormir", "voyager", "manger"], "Moyen de pression."),
    ("Chômage : personnes sans", "emploi cherchant travail", ["vacances", "loisirs", "rêves"], "Indicateur économique."),
    ("PIB mesure la", "production nationale", ["population", "nuages", "sable"], "Valeur des biens/services."),
    ("Secteur primaire :", "agriculture et mines", ["banques", "hôpitaux", "écoles"], "Extraction et culture."),
    ("Secteur secondaire :", "industrie et construction", ["théâtre", "musique", "poésie"], "Transformation."),
    ("Secteur tertiaire :", "services", ["mines", "pêche", "foresterie"], "Commerce, santé, éducation."),
    ("Tourisme en Haïti attire pour", "culture et nature", ["glace permanente", "aurores polaires", "désert"], "Patrimoine et plages."),
    ("Carnaval haïtien célèbre", "culture et musique", ["silence", "interdiction", "censure"], "Fête populaire."),
    ("Rara : tradition musicale", "haïtienne", ["japonaise", "scandinave", "arctique"], "Période pascale."),
    ("Vodou : religion syncrétique", "haïtienne", ["européenne seule", "asiatique", "arctique"], "Héritage africain."),
    ("Catholicisme en Haïti : religion", "majoritaire historique", ["inexistante", "interdite", "unique légale"], "Héritage colonial."),
    ("École fondamentale en Haïti :", "9 années", ["3 années", "20 années", "1 année"], "Cycle fondamental."),
    ("Baccalauréat unique haïtien :", "NS4 (nouveau secondaire)", ["9e fondamentale", "doctorat", "maternelle"], "Fin secondaire."),
    ("Université d'État haïtienne :", "UEH", ["Sorbonne", "Harvard", "Oxford"], "Université d'État."),
    ("Alphabétisation : capacité de", "lire et écrire", ["voler", "nager", "sauter"], "Littératie."),
    ("Genre : égalité hommes-femmes =", "équité", ["discrimination", "exclusion", "interdiction"], "Parité."),
    ("Violence domestique : crime à", "condamner", ["encourager", "ignorer", "célébrer"], "Protection victimes."),
    ("Enfant soldat : violation des", "droits de l'enfant", ["droits du foot", "droits du cinéma", "droits du jeu"], "Interdiction internationale."),
    ("Drogue illicite : commerce", "criminel", ["salutaire", "obligatoire", "scolaire"], "Traite et addiction."),
    ("Gang : groupe criminel", "armé", ["scolaire", "musical", "sportif"], "Sécurité publique."),
    ("Police : maintien de", "l'ordre", ["chaos", "guerre civile", "censure"], "Force de l'ordre."),
    ("Armée haïtiienne dissoute en", "1995", ["1804", "1915", "2010"], "FANH dissoute — réforme."),
    ("Justice : indépendance du", "pouvoir judiciaire", ["exécutif seul", "médias seuls", "armée"], "Séparation pouvoirs."),
    ("Prison : peine privative de", "liberté", ["vacances", "musique", "sport"], "Sanction pénale."),
    ("Peine de mort : interdite en Haïti depuis", "1987 (constitution)", ["1804", "1915", "2000"], "Constitution 1987."),
    ("Citoyen : membre d'un", "État", ["club sportif", "orchestre", "théâtre"], "Nationalité."),
    ("Naturalisation : devenir citoyen par", "procédure légale", ["hasard", "rêve", "chant"], "Acquisition nationalité."),
    ("Passeport : document de", "identité et voyage", ["musique", "cuisine", "danse"], "Voyage international."),
    ("Douane contrôle", "importations", ["rêves", "nuages", "étoiles"], "Fiscalité frontière."),
    ("Smuggling =", "contrebande", ["commerce légal", "don", "aide"], "Passage illicite."),
    ("Patriotisme : amour du", "pays", ["étranger", "rival", "ennemi"], "Loyauté nationale."),
    ("Nationalisme : valorisation de la", "nation", ["colonie", "empire étranger", "invasion"], "Identité nationale."),
    ("Impérialisme : domination", "coloniale ou économique", ["autonomie", "liberté", "égalité"], "Expansion."),
    ("Décolonisation : accès à", "l'indépendance", ["nouvelle colonisation", "guerre", "silence"], "Libération."),
    ("Néocolonialisme : contrôle", "économique indirect", ["direct militaire seul", "aucun", "musical"], "Dépendance."),
    ("Sanction éthique : boycott", "produits", ["tout acheter", "tout cacher", "tout brûler"], "Pression civique."),
    ("Lobby : groupe de", "pression", ["danse", "sport", "cuisine"], "Influence politique."),
    ("Sondage mesure", "opinion", ["température", "altitude", "gravité"], "Opinion publique."),
    ("Élection : choix des", "représentants", ["nuages", "montagnes", "rivières"], "Vote."),
    ("Fraude électorale :", "manipulation du vote", ["transparence", "équité", "honnêteté"], "Crime électoral."),
    ("Coalition : alliance de", "partis", ["montagnes", "océans", "volcans"], "Gouvernement multipartite."),
    ("Opposition : parti qui n'est pas", "au pouvoir", ["toujours au pouvoir", "juge", "maire"], "Contrepouvoir."),
    ("Constitution : loi", "suprême", ["inférieure", "optionnelle", "secrète"], "Cadre juridique."),
    ("Amendement : modification de la", "constitution", ["couleur drapeau", "musique", "danse"], "Révision constitutionnelle."),
    ("Habeas corpus protège contre", "détention illégale", ["vote", "taxe", "route"], "Liberté individuelle."),
    ("Laïcité : séparation État et", "religion", ["commerce", "sport", "musique"], "Neutralité religieuse."),
    ("Pluripartisme : plusieurs", "partis politiques", ["un seul parti", "zéro parti", "armée"], "Démocratie."),
    ("Totalitarisme : contrôle", "total de la société", ["aucun", "partiel léger", "libéral"], "Régime autoritaire."),
    ("Fascisme : idéologie", "autoritaire nationale", ["démocratique", "libertaire", "pacifique"], "Extrême droite."),
    ("Communisme (théorie) : propriété", "collective des moyens de production", ["privée totale", "royale", "nulle"], "Doctrine marxiste."),
    ("Capitalisme : économie de", "marché", ["plan central", "barter seul", "aucun échange"], "Libre entreprise."),
    ("Socialisme : plus d'", "intervention étatique et équité", ["privatisation totale", "dictature", "guerre"], "Modèle mixte."),
    ("Keynes recommande relance par", "investissement public", ["austérité seule", "fermeture", "censure"], "Économie keynésienne."),
    ("Marx analyse les", "classes sociales", ["nuages", "planètes", "étoiles"], "Capital — critique."),
    ("Révolution industrielle : machine à", "vapeur", ["papier", "plume", "crayon"], "Moteur industriel."),
    ("Électricité révolutionne", "industrie et vie quotidienne", ["rien", "seulement foot", "seulement art"], "Second industrial."),
    ("Internet commercialise dans les", "1990s", ["1750s", "1850s", "1650s"], "Réseau mondial."),
    ("Smartphone combine", "téléphone et ordinateur", ["voiture et bateau", "maison et route", "mer et montagne"], "Technologie mobile."),
    ("Intelligence artificielle : apprentissage", "automatique", ["manuel seul", "aucun", "interdit"], "IA/ML."),
    ("Éthique IA : éviter", "biais et surveillance abusive", ["tout usage", "aucune règle", "censure totale"], "Gouvernance tech."),
    ("Open source : code", "ouvert", ["secret", "interdit", "payant seul"], "Logiciel libre."),
    ("Cybersécurité protège", "données", ["nuages", "montagnes", "sables"], "Sécurité numérique."),
    ("Phishing : hameçonnage par", "faux emails", ["sport", "danse", "peinture"], "Fraude en ligne."),
    ("Blockchain enregistre des", "transactions décentralisées", ["rêves", "nuages", "vents"], "Chaîne de blocs."),
    ("Crypto-monnaie : actif", "numérique", ["physique", "papier", "bois"], "Bitcoin etc."),
    ("Métavers : espace", "virtuel immersif", ["réel seul", "interdit", "ancien"], "VR/AR social."),
    ("Télétravail : travail à", "distance", ["usine seule", "mine seule", "champ seul"], "Remote work."),
    ("Gig economy : petits jobs via", "plateformes", ["couronne", "trône", "château"], "Uber, etc."),
    ("Start-up : jeune entreprise", "innovante", ["centenaire", "étatique", "coloniale"], "Innovation."),
    ("IPO : introduction en", "bourse", ["prison", "école", "hôpital"], "Marché actions."),
    ("NASDAQ : marché", "technologique (USA)", ["agricole", "forestier", "pêche"], "Bourse tech."),
    ("Brexit impacte", "UK-EU commerce", ["lune", "mars", "soleil"], "Relations UK."),
    ("Guerre Ukraine-Russie escalade depuis", "2022", ["1991", "2001", "1804"], "Conflit armé."),
    ("OTAN aide membres en cas d'", "attaque", ["fête", "sport", "musique"], "Article 5."),
    ("Sanctions Russie liées à", "guerre", ["sport", "art", "cuisine"], "Mesures occidentales."),
    ("Chine : politique « une seule »", "Chine", ["deux Chines", "trois Chines", "zéro"], "Taiwan question."),
    ("Japon : capitale", "Tokyo", ["Osaka", "Kyoto", "Sapporo"], "Capitale."),
    ("Inde : capitale", "New Delhi", ["Mumbai", "Calcutta", "Chennai"], "Capitale administrative."),
    ("Brésil : capitale", "Brasília", ["Rio", "São Paulo", "Salvador"], "Capitale fédérale."),
    ("Afrique : plus grand pays en superficie", "Algérie", ["Rwanda", "Lesotho", "Swaziland"], "2,38M km²."),
    ("Nigeria : population", "la plus grande d'Afrique", ["la plus petite", "nulle", "zéro"], ">D 200M."),
    ("Sahara : plus grand", "désert chaud", ["océan", "glacier", "forêt"], "Désert nord-africain."),
    ("Nil : fleuve", "africain", ["européen", "asiatique", "arctique"], "Long fleuve."),
    ("Congo : fleuve et", "forêt tropicale", ["désert", "glacier", "steppe"], "Bassin du Congo."),
    ("Andes : chaîne", "sud-américaine", ["européenne", "africaine", "asiatique"], "Montagnes."),
    ("Amazonie : plus grande", "forêt tropicale", ["désert", "glacier", "steppe"], "Forêt amazonienne."),
    ("Antarctique : continent", "glacé", ["chaud", "tropical", "désertique chaud"], "Pôle Sud."),
    ("Arctique : région", "polaire nord", ["équatoriale", "tropicale", "tempérée"], "Pôle Nord."),
    ("Pacifique : plus grand", "océan", ["lac", "ruisseau", "fontaine"], "Océan Pacifique."),
    ("Méditerranée relie", "Europe, Afrique, Asie", ["Amérique, Antarctique", "lune, mars", "rien"], "Mer intercontinentale."),
    ("Canal de Panama en", "Panama", ["Haïti", "France", "Kenya"], "Amérique centrale."),
    ("Suez en", "Égypte", ["Haïti", "Jamaïque", "Cuba"], "Mer Rouge."),
    ("Strait of Hormuz : pétrole", "moyen-oriental", ["arctique", "antarctique", "lunaire"], "Géopolitique."),
    ("OPEP contrôle part de", "pétrole mondial", ["eau", "air", "nuages"], "Cartel pétrolier."),
    ("Énergie fossile : charbon, pétrole,", "gaz", ["vent", "soleil", "marée"], "Combustibles."),
    ("Nucléaire utilise", "uranium", ["bois", "papier", "plastique"], "Fission."),
    ("Fusion nucléaire : énergie des", "étoiles", ["nuages", "rochers", "sables"], "Réaction stellaire."),
    ("GPS utilise satellites pour", "position", ["couleur", "odeur", "taste"], "Géolocalisation."),
    ("5G : réseau mobile", "rapide", ["ancien", "interdit", "nul"], "Cinquième génération."),
    ("IoT : objets", "connectés", ["déconnectés", "interdits", "cassés"], "Internet des objets."),
    ("Big data : analyse de", "grandes données", ["zéro donnée", "une donnée", "rêves"], "Analytics."),
    ("Cloud : stockage", "distant", ["local seul", "papier", "pierre"], "Informatique en nuage."),
    ("Ransomware : rançongiciel", "malveillant", ["bénéfique", "sportif", "musical"], "Cyberattaque."),
    ("Deepfake : vidéo", "manipulée par IA", ["authentique garanti", "papier", "bois"], "Faux média."),
    ("GDPR : protection des données en", "UE", ["lune", "mars", "océan"], "Règlement européen."),
    ("Haïti — code téléphonique international :", "+509", ["+1", "+33", "+44"], "Indicatif HT."),
    ("Domaine internet Haïti :", ".ht", [".us", ".fr", ".uk"], "ccTLD."),
    ("Port international principal :", "Port international du Cap-Haïtien / PAP", ["Tokyo", "Londres", "Paris"], "Ports haïtiens."),
    ("Aéroport principal PAP :", "Toussaint Louverture", ["Charles de Gaulle", "Heathrow", "JFK"], "Aéroport international."),
    ("Route nationale 1 relie", "Ouest au Nord", ["lune à mars", "mer à ciel", "rêve à rêve"], "Axe routier."),
    ("Électricité EDH :", "Électricité d'Haïti", ["EDF", "Con Edison", "National Grid"], "Service public."),
    ("Digue : structure contre", "inondations", ["musique", "danse", "peinture"], "Protection eau."),
    ("Irrigation : apport d'", "eau aux cultures", ["sable", "roche", "métal"], "Agriculture."),
    ("Sécurité alimentaire : accès à", "nourriture suffisante", ["aucune", "interdit", "censure"], "Faim zéro."),
    ("Malnutrition : manque de", "nutriments", ["eau seule", "air seul", "lumière"], "Santé."),
    ("Obésité : excès de", "masse grasse", ["muscles", "os", "cheveux"], "Santé publique."),
    ("Diabète lié au", "sucre / insuline", ["sport seul", "musique", "peinture"], "Maladie chronique."),
    ("Hypertension : pression artérielle", "élevée", ["basse", "nulle", "normale"], "Santé."),
    ("COVID-19 déclarée pandémie en", "2020", ["1804", "1914", "1991"], "Coronavirus."),
    ("Vaccin : stimule", "immunité", ["peur", "guerre", "censure"], "Immunisation."),
    ("OMS : Organisation mondiale de la", "Santé", ["Guerre", "Foot", "Musique"], "WHO."),
    ("UNICEF aide les", "enfants", ["entreprises", "dictateurs", "armées"], "Fonds ONU enfance."),
    ("HCR : réfugiés de l'", "ONU", ["FIFA", "NATO", "NBA"], "UNHCR."),
    ("FAO : organisation pour", "alimentation et agriculture", ["foot", "cinéma", "mode"], "FAO."),
    ("PAM : programme alimentaire", "mondial", ["lunaire", "martien", "solaire"], "WFP."),
    ("Greenpeace défend", "environnement", ["pollution", "guerre", "censure"], "ONG écologiste."),
    ("Amnesty International défend", "droits humains", ["dictature", "torture", "censure"], "ONG."),
    ("Transparency International combat", "corruption", ["transparence", "honnêteté", "équité"], "Indice corruption."),
    ("Nobel de la paix récompense", "contribution à la paix", ["guerre", "violence", "dictature"], "Prix Nobel."),
    ("Olympiques modernes relancés par", "Pierre de Coubertin", ["Napoléon", "Hitler", "Staline"], "1896 Athènes."),
    ("Coupe du monde FIFA tous les", "4 ans", ["1 an", "10 ans", "20 ans"], "Tournoi football."),
    ("JO se tiennent tous les", "4 ans", ["2 ans", "5 ans", "8 ans"], "Jeux olympiques."),
    ("Haïti foot — sélection :", "Grenadiers", ["All Blacks", "Samurais", "Les Bleus"], "Équipe nationale."),
    ("Basket NBA aux", "États-Unis", ["Haïti seul", "lune", "mars"], "Ligue US."),
    ("Tour de France : cyclisme en", "France", ["océan", "espace", "lune"], "Grande boucle."),
    ("Marathon : course de", "42,195 km", ["1 km", "100 m", "10 m"], "Distance officielle."),
    ("Fair play :", "jeu loyal", ["triche", "violence", "corruption"], "Éthique sportive."),
    ("Dopage : substances", "interdites", ["obligatoires", "salutaires", "neutres"], "Anti-dopage."),
    ("Médias sociaux : Facebook, Instagram,", "TikTok", ["pierre", "bois", "fer"], "Réseaux."),
    ("Fake news :", "fausses informations", ["vérité", "science", "stats"], "Désinformation."),
    ("Journalisme vérifie les", "sources", ["rêves", "mensonges", "secrets"], "Démarche pro."),
    ("Photoshop peut", "modifier images", ["rien", "interdire", "casser"], "Édition."),
    ("Podcast : audio", "en ligne", ["papier", "pierre", "sable"], "Média audio."),
    ("Streaming : diffusion", "continue en ligne", ["cassette", "vinyle seul", "pierre"], "Netflix etc."),
    ("E-commerce : commerce", "en ligne", ["forêt", "montagne", "océan"], "Amazon etc."),
    ("QR code stocke", "information numérique", ["eau", "sable", "air"], "Code barre 2D."),
    ("Wi-Fi : connexion", "sans fil", ["câble seul", "pierre", "bois"], "Réseau local."),
    ("Bluetooth : connexion", "courte distance", ["satellite", "lune", "mars"], "Sans fil."),
    ("USB : connecteur", "universel", ["secret", "interdit", "cassé"], "Port standard."),
    ("PDF : document", "portable", ["audio", "vidéo seule", "odeur"], "Format Adobe."),
    ("Excel : tableur", "Microsoft", ["peinture", "musique", "danse"], "Feuille calcul."),
    ("PowerPoint :", "présentations", ["jeux seuls", "films seuls", "romans"], "Slides."),
    ("Word : traitement de", "texte", ["image seule", "son seul", "vidéo seule"], "Document."),
    ("Google : moteur de", "recherche", ["cuisine", "sport", "danse"], "Search."),
    ("Wikipedia : encyclopédie", "collaborative", ["secrète", "payante", "interdite"], "Wiki."),
    ("Creative Commons : licences", "ouvertes", ["fermées", "secrètes", "interdites"], "Partage."),
    ("Linux : système", "open source", ["fermé", "secret", "interdit"], "OS libre."),
    ("Windows : OS de", "Microsoft", ["Apple seul", "lune", "mars"], "PC dominant."),
    ("macOS : OS d'", "Apple", ["Microsoft", "Google", "Amazon"], "Macintosh."),
    ("Android : OS", "mobile Google", ["desktop seul", "serveur seul", "lune"], "Smartphones."),
    ("iOS : OS", "iPhone", ["Android", "Windows phone", "Symbian"], "Apple mobile."),
    ("App store distribue", "applications", ["nourriture", "vêtements", "meubles"], "Marketplace."),
    ("API permet", "communication logicielle", ["silence", "censure", "guerre"], "Interface."),
    ("Bug :", "erreur logicielle", ["feature", "cadeau", "bonus"], "Défaut code."),
    ("Patch : correctif", "logiciel", ["virus", "malware", "ransom"], "Mise à jour."),
    ("Backup :", "sauvegarde", ["suppression", "effacement", "destruction"], "Copie sécurité."),
    ("Firewall : pare-feu", "réseau", ["porte ouverte", "virus", "spam"], "Sécurité."),
    ("VPN : réseau", "privé virtuel", ["public ouvert", "radio", "TV"], "Anonymisation."),
    ("Captcha vérifie", "humain vs bot", ["couleur", "odeur", "taste"], "Sécurité web."),
    ("Cookie web stocke", "données navigateur", ["nourriture", "bois", "métal"], "Tracking."),
    ("HTTPS : connexion", "sécurisée", ["non sécurisée", "ouverte", "cassée"], "TLS."),
    ("URL : adresse", "web", ["postale", "rêve", "nuage"], "Lien."),
    ("HTML : langage", "balises web", ["musique", "danse", "peinture"], "Structure page."),
    ("CSS : style", "visuel web", ["son", "odeur", "taste"], "Design."),
    ("JavaScript : langage", "web interactif", ["pierre", "bois", "fer"], "Script client."),
    ("Python : langage", "programmation populaire", ["danse", "sport", "cuisine"], "Langage."),
    ("SQL : langage", "bases de données", ["peinture", "musique", "danse"], "Requêtes."),
    ("Git : gestion de", "versions code", ["nourriture", "vêtements", "meubles"], "VCS."),
    ("GitHub : plateforme", "code open source", ["restaurant", "hôtel", "musée"], "Forge."),
    ("Agile : méthode", "itérative projet", ["waterfall seule", "chaos", "rien"], "Scrum/Kanban."),
    ("DevOps : dev +", "opérations", ["marketing", "danse", "sport"], "CI/CD."),
    ("UI : interface", "utilisateur", ["backend", "database", "kernel"], "Frontend."),
    ("UX : expérience", "utilisateur", ["serveur", "disque", "câble"], "Design."),
    ("Responsive : s'adapte à", "écran", ["odeur", "taste", "son seul"], "Mobile-first."),
    ("Accessibility : accessibilité pour", "tous", ["riches seuls", "adultes seuls", "hommes seuls"], "A11y."),
    ("Dark mode : thème", "sombre", ["clair seul", "invisible", "cassé"], "UI."),
    ("Emoji : pictogramme", "unicode", ["mot", "nombre", "équation"], "😀."),
    ("Hashtag # organise", "contenu social", ["papier", "bois", "pierre"], "Tag."),
    ("Influenceur : marketing", "social", ["politique seul", "militaire", "judiciaire"], "Creator."),
    ("NFT : jeton", "non fongible", ["papier", "bois", "pierre"], "Crypto art."),
    ("Web3 : internet", "décentralisé", ["centralisé seul", "fermé", "secret"], "Blockchain web."),
    ("Méta données : données sur", "données", ["rien", "rêves", "nuages"], "Metadata."),
    ("Algorithme : suite d'", "instructions", ["rêves", "nuages", "vents"], "Procédure."),
    ("Machine learning apprend depuis", "données", ["rien", "rêves", "nuages"], "ML."),
    ("Neural network : réseau de", "neurones artificiels", ["pierre", "bois", "sable"], "Deep learning."),
    ("Turing test évalue", "intelligence machine", ["vitesse", "couleur", "odeur"], "IA."),
    ("Robot industriel automatise", "usine", ["théâtre", "poésie", "danse"], "Automation."),
    ("Drone : véhicule", "aérien sans pilote", ["sous-marin", "souterrain", "lunaire"], "UAV."),
    ("Tesla : voitures", "électriques", ["charrettes", "chevaux", "voiliers"], "EV."),
    ("SpaceX : entreprise", "spatial privé", ["restaurant", "hôtel", "musée"], "Falcon."),
    ("NASA : agence spatiale", "USA", ["Haïti", "Jamaïque", "Cuba"], "Space."),
    ("ISS : station spatiale", "internationale", ["sous-marine", "souterraine", "lunaire seule"], "Orbite."),
    ("Mars : planète", "rouge", ["bleue", "verte", "jaune"], "Quatrième planète."),
    ("Lune : satellite de la", "Terre", ["Mars", "Jupiter", "Soleil"], "Satellite."),
    ("Soleil : étoile de la", "Terre", ["Lune", "Mars", "Jupiter"], "Étoile."),
    ("Galaxie : Milky Way =", "Voie lactée", ["Andromède seule", "lune", "mars"], "Notre galaxie."),
    ("Big Bang : origine de", "l'univers", ["la Terre seule", "la lune", "mars"], "Cosmologie."),
    ("Relativité : Einstein — espace et", "temps", ["couleur", "odeur", "taste"], "Physique."),
    ("Quantum : physique des", "particules", ["montagnes", "océans", "nuages"], "QM."),
    ("ADN : acide désoxyribonucléique —", "génétique", ["musique", "danse", "peinture"], "Biologie."),
    ("CRISPR : édition", "génique", ["musique", "danse", "peinture"], "Biotech."),
    ("Stem cells : cellules", "souches", ["pierre", "bois", "sable"], "Médecine."),
    ("Antibiotique combat", "bactéries", ["virus seuls", "rochers", "nuages"], "Médecine."),
    ("Vaccin ARN messager utilisé pour", "COVID", ["pierre", "bois", "sable"], "mRNA."),
    ("Herd immunity = immunité de", "groupe", ["individu seul", "rocher", "nuage"], "Épidémiologie."),
    ("Epidémie : propagation", "rapide maladie", ["lente", "nulle", "inverse"], "Santé publique."),
    ("Pandémie : épidémie", "mondiale", ["locale", "familiale", "nulle"], "Global."),
    ("Quarantaine : isolement", "14-21 jours typique", ["1 seconde", "0 jour", "100 ans"], "Santé."),
    ("Masque protège contre", "gouttelettes", ["gravité", "magnétisme", "lumière"], "COVID."),
    ("Distanciation sociale réduit", "transmission", ["augmente", "ignore", "célèbre"], "Santé."),
    ("Telemedicine : soins à", "distance", ["pierre", "bois", "sable"], "E-santé."),
    ("WHO headquarters :", "Genève", ["Port-au-Prince", "Jacmel", "Les Cayes"], "Suisse."),
    ("CDC : centres contrôle", "maladies (USA)", ["foot", "musique", "danse"], "Santé US."),
    ("FDA approuve", "médicaments (USA)", ["films", "chansons", "jeux"], "Régulateur."),
    ("HIPAA protège données", "santé (USA)", ["sport", "musique", "danse"], "Privacy."),
    ("GDPR protège données", "personnelles (UE)", ["rochers", "nuages", "sables"], "Privacy EU."),
    ("Haïti — ministère éducation :", "MENFP", ["NBA", "FIFA", "NATO"], "Éducation nationale."),
    ("MENFP supervise", "écoles fondamentales et secondaires", ["restaurants", "hôtels", "musées"], "Secteur éducatif."),
    ("9e année fondamentale : niveau", "terminal fondamental", ["universitaire", "doctorat", "maternelle"], "Fin fondamental."),
    ("NS4 : nouveau secondaire —", "4 ans", ["1 an", "20 ans", "0 an"], "Cycle secondaire."),
    ("Philosophie en NS4 : discipline", "bac", ["maternelle", "primaire", "aucune"], "Programme."),
    ("Économie en NS4 : discipline", "bac", ["maternelle", "primaire", "aucune"], "Programme."),
    ("Examens nationaux haïtiens organisés par", "MENFP", ["FIFA", "NBA", "NATO"], "État central."),
    ("ExamHaiti archive des", "examens officiels", ["films", "chansons", "jeux"], "Ressource éducative."),
    ("OU TOU BON aide élèves haïtiens en", "révision", ["guerre", "censure", "dictature"], "Plateforme éducative."),
]


def _from_static() -> list[dict]:
    out = []
    for q, correct, wrongs, expl in STATIC:
        opts = [correct] + wrongs[:3]
        out.append(
            make_q(
                q,
                opts,
                0,
                expl,
                "Histoire",
                "moyen",
            )
        )
    return out


def _combo_depts(rng: random.Random) -> list[dict]:
    out = []
    for dept, chef in HAITI_DEPTS:
        others = [c for _, c in HAITI_DEPTS if c != chef]
        q = f"Quelle ville est le chef-lieu du département {dept} ?"
        wrongs = rng.sample(others, 3)
        opts, ci = shuffle_wrong_options(chef, wrongs, rng)
        out.append(
            make_q(
                q,
                opts,
                ci,
                f"{chef} est le chef-lieu du {dept}.",
                "Géographie haïtienne",
                "facile",
            )
        )
    return out


def _combo_wwii(rng: random.Random) -> list[dict]:
    out = []
    facts = [
        ("Quand commence la Seconde Guerre mondiale ?", "1939", ["1914", "1945", "1960"]),
        ("Quand se termine la Seconde Guerre mondiale ?", "1945", ["1939", "1918", "1991"]),
        ("Alliance Allemagne-Italie-Japon :", "Axe", ["Alliés", "CARICOM", "OTAN"]),
        ("Campagne du D-Day en :", "1944", ["1939", "1950", "1962"]),
        ("Conférence de Yalta en :", "1945", ["1939", "1918", "2001"]),
        ("Bombe atomique sur Hiroshima en :", "1945", ["1939", "1955", "1914"]),
        ("Holocauste : principale cible", "Juifs", ["athlètes", "musiciens", "peintres"]),
        ("Régime nazi dirigé par", "Hitler", ["Churchill", "Roosevelt", "Stalin"]),
        ("USA entre en guerre après", "Pearl Harbor 1941", ["WWI 1914", "Révolution 1789", "Guerre froide"]),
        ("URSS : capitale historique guerre", "Moscou", ["Paris", "London", "Rome"]),
    ]
    for q, c, w in facts:
        opts, ci = shuffle_wrong_options(c, w, rng)
        out.append(make_q(q, opts, ci, f"Réponse : {c}.", "Seconde Guerre mondiale", "moyen"))
    return out


def generate_histoire(rng: random.Random, seen: set[str]) -> list[dict]:
    out = _from_static() + _combo_depts(rng) + _combo_wwii(rng)
    rng.shuffle(out)
    return out
