"""Build verified 9e AF quiz JSON (NS4 schema). Only QCM with a certain answer."""
from __future__ import annotations

import json
from pathlib import Path

DB = Path(__file__).resolve().parents[1] / "database"


def q(qid, category, difficulty, timer, question, correct, explanation, options):
    return {
        "id": qid,
        "category": category,
        "difficulty": difficulty,
        "timer_seconds": timer,
        "question": question,
        "correct": correct,
        "explanation": explanation,
        "options": options,
    }


MATH = [
    q("M9E1", "Arithmétique", "facile", 25,
      "Lequel des nombres suivants n'est pas un diviseur de 14 ?",
      "B",
      "Les diviseurs positifs de 14 sont 1, 2, 7 et 14. 4 ne divise pas 14 (14 ÷ 4 = 3,5).",
      ["2", "4", "7", "14"]),
    q("M9E4", "Géométrie", "moyen", 35,
      "Si A, E et F sont trois points distincts d'un cercle de diamètre [AE], quelle est alors la nature du triangle AEF ?",
      "D",
      "Tout triangle inscrit dans un cercle dont un côté est un diamètre est rectangle au sommet opposé au diamètre (théorème de Thalès). Donc AEF est rectangle en F.",
      ["rectangle en A", "isocèle en E", "isocèle en A", "rectangle en F"]),
    q("M9E5", "Pourcentages", "facile", 25,
      "Quel est, en pourcentage, la valeur de la fraction 3/5 ?",
      "C",
      "(3/5) × 100 = 60. Donc 3/5 = 60 %.",
      ["35 %", "30 %", "60 %", "20 %"]),
    q("M9E9", "Géométrie", "moyen", 30,
      "Laquelle des figures géométriques suivantes a des diagonales perpendiculaires et de même longueur ?",
      "D",
      "Le carré a des diagonales à la fois perpendiculaires et de même longueur. Le losange a des diagonales perpendiculaires mais pas forcément égales ; le rectangle a des diagonales égales mais pas perpendiculaires.",
      ["Le losange", "Le trapèze", "Le rectangle", "Le carré"]),
    q("M9E10", "Géométrie", "moyen", 30,
      "Dans quel triangle les droites remarquables sont à la fois hauteurs, médianes, médiatrices et bissectrices ?",
      "C",
      "Dans un triangle équilatéral, hauteurs, médianes, médiatrices et bissectrices coïncident.",
      ["Triangle rectangle", "Triangle isocèle", "Triangle équilatéral", "Triangle rectangle-isocèle"]),
    q("M9E11", "Grandeurs", "moyen", 40,
      "Quel est le volume d'un récipient qu'un robinet débitant 20 L/min remplit en 2 heures ?",
      "A",
      "2 h = 120 min. Volume = 20 × 120 = 2400 L = 2,4 m³.",
      ["2,4 m³", "10 m³", "1,2 m³", "4 m³"]),
    q("M9E12", "Géométrie dans l'espace", "moyen", 30,
      "Laquelle des formules suivantes est celle de l'aire latérale d'un cylindre ?",
      "C",
      "L'aire latérale d'un cylindre est 2πrh (rectangle obtenu en déroulant le tube). πr²h est le volume.",
      ["πr²h", "πrh", "2πrh", "πr²"]),
    q("M9E13", "Géométrie", "facile", 25,
      "L'orthocentre d'un triangle est le point de rencontre des :",
      "C",
      "L'orthocentre est le point de concours des hauteurs. Les médianes se coupent au centre de gravité, les médiatrices au centre du cercle circonscrit, les bissectrices au centre du cercle inscrit.",
      ["Bissectrices", "Médianes", "Hauteurs", "Médiatrices"]),
    q("M9E14", "Statistiques", "moyen", 30,
      "La médiane de la série : 13 ; 21 ; 19 ; 18 ; 27 ; 15 est :",
      "C",
      "Série ordonnée : 13, 15, 18, 19, 21, 27. Six valeurs : médiane = (18+19)/2 = 18,5.",
      ["19", "18", "18,5", "19,6"]),
    q("M9E15", "Géométrie", "facile", 25,
      "Si une droite est sécante à un cercle, alors :",
      "A",
      "Une sécante coupe le cercle en deux points distincts. Un seul point commun correspond à une tangente.",
      ["Ils ont deux points communs", "Ils ont un point commun", "Ils n'ont aucun point commun", "La droite se trouve à l'extérieur du cercle"]),
    q("M9E16", "Géométrie", "facile", 25,
      "Le point de rencontre des médianes d'un triangle est appelé :",
      "C",
      "Le point de concours des médianes est le centre de gravité (barycentre).",
      ["Orthocentre", "Centre du cercle inscrit", "Centre de gravité", "Centre du cercle circonscrit"]),
    q("M9E17", "Pourcentages", "facile", 20,
      "50 % d'une somme d'argent représente :",
      "D",
      "50 % = 50/100 = 1/2 : la moitié de la somme.",
      ["Son double", "Son quart", "Son tiers", "Sa moitié"]),
    q("M9E18", "Algèbre", "facile", 25,
      "On donne H = 5x − 4x − 2x − 3x ; l'expression réduite de H est :",
      "B",
      "5x − 4x − 2x − 3x = (5−4−2−3)x = −4x.",
      ["4x", "−4x", "120x", "−120x"]),
    q("M9E19", "Géométrie", "facile", 25,
      "Que peut-on dire d'un cercle et d'une droite qui n'ont aucun point commun ?",
      "D",
      "Aucun point commun : la droite est extérieure au cercle (elle n'est ni sécante ni tangente).",
      ["La droite est tangente au cercle", "La distance entre le centre du cercle et la droite est nulle", "La droite et le cercle sont sécants", "La droite est extérieure au cercle"]),
    q("M9E20", "Géométrie", "moyen", 30,
      "Si deux cercles de centres O et O' et de rayons r et r' vérifient OO' = r + r', alors :",
      "C",
      "Lorsque la distance des centres est égale à la somme des rayons, les cercles sont tangents extérieurement.",
      ["Ils sont concentriques", "Ils sont sécants", "Ils sont tangents extérieurement", "Ils sont extérieurs l'un à l'autre"]),
    q("M9E21", "Géométrie", "facile", 25,
      "Lequel de ces points est le point de rencontre des droites perpendiculaires aux côtés d'un triangle en leur milieu ?",
      "A",
      "Les perpendiculaires aux côtés en leur milieu sont les médiatrices ; elles se coupent au centre du cercle circonscrit.",
      ["Le centre du cercle circonscrit au triangle", "Le centre du cercle inscrit dans le triangle", "L'orthocentre du triangle", "Le centre de gravité du triangle"]),
    q("M9E22", "Géométrie", "facile", 25,
      "Le point d'intersection des médiatrices d'un triangle est :",
      "C",
      "Les médiatrices se coupent au centre du cercle circonscrit (équidistant des trois sommets).",
      ["l'orthocentre du triangle", "le centre du cercle inscrit au triangle", "le centre du cercle circonscrit au triangle", "le centre de gravité du triangle"]),
    q("M9E23", "Algèbre", "moyen", 30,
      "L'expression factorisée de f(x) = 4x² − 25 est :",
      "C",
      "4x² − 25 = (2x)² − 5² = (2x − 5)(2x + 5) (identité remarquable a² − b²).",
      ["(4x − 5)(2x + 5)", "(4x − 5)²", "(2x − 5)(2x + 5)", "(2x − 5)²"]),
    q("M9E24", "Pourcentages", "facile", 25,
      "Diminuer x de 5 % c'est multiplier x par :",
      "C",
      "Diminuer de 5 % revient à garder 95 % du nombre : x × 0,95.",
      ["0,05", "1,05", "0,95", "0,5"]),
    q("M9E25", "Géométrie", "facile", 20,
      "Quel nom donne-t-on au côté opposé à l'angle droit d'un triangle rectangle ?",
      "B",
      "Le côté opposé à l'angle droit s'appelle l'hypoténuse.",
      ["hauteur", "hypoténuse", "médiane", "bissectrice"]),
    q("M9E26", "Grandeurs", "facile", 25,
      "Quelle grandeur détermine-t-on lorsqu'on fait le quotient du volume de liquide écoulé par la durée ?",
      "C",
      "Débit = volume / durée.",
      ["la masse", "la vitesse", "le débit", "le poids"]),
    q("M9E27", "Géométrie", "facile", 20,
      "La droite d'un triangle qui passe par un sommet et le milieu du côté opposé s'appelle :",
      "B",
      "C'est la définition de la médiane. La médiatrice est perpendiculaire au milieu ; la hauteur est perpendiculaire au côté opposé.",
      ["Médiatrice", "Médiane", "Hauteur", "Bissectrice"]),
    q("M9E28", "Arithmétique", "moyen", 30,
      "Le nombre qu'il faut ajouter à 2/7 pour obtenir 3 est :",
      "C",
      "3 − 2/7 = 21/7 − 2/7 = 19/7.",
      ["5/7", "6/7", "19/7", "21/7"]),
    q("M9E29", "Géométrie", "moyen", 30,
      "G est le centre de gravité du triangle ABC et AI = 7,5 cm (I milieu de [BC]). La longueur AG est :",
      "D",
      "Sur une médiane, AG = (2/3) × AI = (2/3) × 7,5 = 5 cm.",
      ["2,5 cm", "3 cm", "4,5 cm", "5 cm"]),
    q("M9E30", "Géométrie", "facile", 25,
      "Laquelle des égalités suivantes traduit que le triangle EFG est rectangle en E ?",
      "B",
      "Le théorème de Pythagore : le carré de l'hypoténuse (côté opposé à E, donc FG) égale la somme des carrés des deux autres côtés : EG² = EF² + FG² n'est vrai que si l'angle droit est en G. Rectangle en E signifie hypoténuse FG : FG² = EF² + EG².",
      ["EF² = FG² + EG²", "FG² = EF² + EG²", "EF² = EG² − FG²", "EG² = EF² − FG²"]),
    q("M9E31", "Statistiques", "facile", 30,
      "Si les notes sur 30 d'un élève pour six tests sont 12, 18, 15, 10, 16 et 13, quelle est alors sa moyenne ?",
      "C",
      "Somme = 12+18+15+10+16+13 = 84. Moyenne = 84/6 = 14.",
      ["84", "18", "14", "12"]),
    q("M9E32", "Géométrie", "facile", 20,
      "Quelle est la mesure du supplément d'un angle aigu mesurant 75° ?",
      "A",
      "Deux angles supplémentaires ont pour somme 180°. 180° − 75° = 105°.",
      ["105°", "15°", "25°", "150°"]),
    q("M9E33", "Géométrie", "facile", 25,
      "Quel nom donne-t-on au point de rencontre des trois hauteurs d'un triangle ?",
      "C",
      "Le point de concours des hauteurs est l'orthocentre.",
      ["centre de gravité", "centre du cercle inscrit", "orthocentre", "centre du cercle circonscrit"]),
    q("M9E34", "Algèbre", "moyen", 25,
      "L'expression (9 + 2x)(9 − 2x) est égale à :",
      "B",
      "Identité (a+b)(a−b) = a² − b² avec a = 9 et b = 2x : 81 − 4x².",
      ["18 − 4x²", "81 − 4x²", "81 − 36x + 4x²", "81 + 4x²"]),
    q("M9E35", "Géométrie", "facile", 25,
      "Un encadrement de la mesure d'un angle rentrant A est :",
      "D",
      "Un angle rentrant (concave) mesure plus de 180° et moins de 360°. Parmi les choix, 180° < A < 270° est le seul encadrement d'angle rentrant.",
      ["0° < A < 90°", "90° < A < 180°", "120° < A < 180°", "180° < A < 270°"]),
    q("M9E36", "Géométrie", "facile", 20,
      "Les trois droites qui déterminent le centre de gravité d'un triangle s'appellent :",
      "C",
      "Le centre de gravité est le point de concours des médianes.",
      ["bissectrices", "médiatrices", "médianes", "hauteurs"]),
    q("M9E37", "Géométrie", "facile", 20,
      "Le centre du cercle inscrit dans un triangle est le point de rencontre de ses :",
      "A",
      "Les bissectrices se coupent au centre du cercle inscrit.",
      ["bissectrices", "médianes", "médiatrices", "hauteurs"]),
    q("M9E38", "Géométrie", "moyen", 30,
      "Si AB = 9, BC = 15 et AC = 12, alors ABC est un triangle :",
      "B",
      "9² + 12² = 81 + 144 = 225 = 15² = BC². Donc rectangle en A (Pythagore).",
      ["rectangle isocèle", "rectangle", "quelconque", "isocèle"]),
    q("M9E39", "Grandeurs", "facile", 25,
      "Pierre fait 135 km en 1 h 30 min. Sa vitesse moyenne en km/h est :",
      "D",
      "1 h 30 min = 1,5 h. v = 135 / 1,5 = 90 km/h.",
      ["202,5 km/h", "175,5 km/h", "103 km/h", "90 km/h"]),
    q("M9E40", "Géométrie", "facile", 25,
      "LMNOPQ est un hexagone régulier. La mesure de chacun de ses angles intérieurs est :",
      "D",
      "Angle intérieur d'un hexagone régulier : ((6−2)×180°)/6 = 120°.",
      ["60°", "90°", "110°", "120°"]),
    q("M9E41", "Géométrie", "facile", 20,
      "Le centre de gravité d'un triangle est le point de rencontre de ses :",
      "B",
      "Les médianes se coupent au centre de gravité.",
      ["hauteurs", "médianes", "bissectrices", "médiatrices"]),
    q("M9E42", "Géométrie", "facile", 20,
      "Un angle dont la mesure est strictement supérieure à 90° et strictement inférieure à 180° est un angle :",
      "B",
      "C'est la définition d'un angle obtus.",
      ["aigu", "obtus", "plat", "droit"]),
    q("M9E43", "Géométrie", "facile", 20,
      "Le nombre d'axes de symétrie d'un carré est :",
      "C",
      "Un carré a 4 axes de symétrie : deux médianes et deux diagonales.",
      ["8", "2", "4", "6"]),
    q("M9E44", "Géométrie", "facile", 25,
      "La longueur de la diagonale d'un rectangle mesurant 9 cm de long et 12 cm de large est :",
      "A",
      "d² = 9² + 12² = 81 + 144 = 225, donc d = 15 cm.",
      ["15 cm", "8 cm", "30 cm", "21 cm"]),
    q("M9E45", "Géométrie", "facile", 25,
      "Un triangle ABC est rectangle en A, tel que AB = 8 cm, BC = 10 cm. Le côté AC est égal à :",
      "A",
      "AC² = BC² − AB² = 100 − 64 = 36, donc AC = 6 cm.",
      ["6 cm", "18 cm", "2 cm", "36 cm"]),
    q("M9E46", "Grandeurs", "facile", 25,
      "Un récipient de 160 litres a été remplí en 40 minutes. Le débit du robinet est :",
      "A",
      "Débit = 160 L / 40 min = 4 L/min.",
      ["4 L/min", "8 L/min", "16 L/min", "13 L/min"]),
    q("M9E47", "Géométrie", "facile", 20,
      "Le supplément d'un angle est l'angle qu'il faut lui ajouter pour obtenir :",
      "B",
      "Deux angles supplémentaires ont pour somme 180°, c'est-à-dire un angle plat.",
      ["un angle droit", "un angle plat", "un angle obtus", "un angle nul"]),
    q("M9E48", "Géométrie", "moyen", 25,
      "Dans un cercle de centre O, l'angle inscrit xMy et l'angle au centre xOy interceptent le même arc. Si xOy mesure 76°, alors la mesure de l'angle xMy est :",
      "B",
      "L'angle inscrit mesure la moitié de l'angle au centre qui intercepte le même arc : 76° / 2 = 38°.",
      ["76°", "38°", "152°", "284°"]),
    q("M9E49", "Géométrie", "facile", 25,
      "Si [OZ] est la bissectrice de l'angle xOy et xOz = 30°, alors l'angle yOz mesure :",
      "C",
      "La bissectrice partage l'angle en deux angles égaux, donc yOz = xOz = 30°.",
      ["15°", "60°", "30°", "45°"]),
    q("M9E50", "Géométrie", "facile", 20,
      "Deux angles A et B sont correspondants. Si l'angle B mesure 20°, alors l'angle A mesure :",
      "D",
      "Les angles correspondants formés par deux droites parallèles coupées par une sécante sont égaux : A = 20°.",
      ["160°", "40°", "30°", "20°"]),
    q("M9E51", "Géométrie", "facile", 20,
      "Le complément d'un angle est 40°. La mesure de cet angle est :",
      "D",
      "Deux angles complémentaires ont pour somme 90°. L'angle mesure 90° − 40° = 50°.",
      ["140°", "40°", "80°", "50°"]),
    q("M9E52", "Géométrie", "facile", 20,
      "[OZ] est la bissectrice de l'angle xOy. Si xOz = 30°, alors l'angle xOy est égal à :",
      "C",
      "xOy = 2 × 30° = 60°.",
      ["15°", "30°", "60°", "45°"]),
    q("M9E53", "Géométrie", "facile", 25,
      "Dans un triangle rectangle, si la longueur de la médiane relative à l'hypoténuse est 4 cm, alors la longueur de l'hypoténuse est :",
      "C",
      "Dans un triangle rectangle, la médiane relative à l'hypoténuse vaut la moitié de l'hypoténuse. Donc hypoténuse = 8 cm.",
      ["2 cm", "12 cm", "8 cm", "6 cm"]),
    q("M9E54", "Pourcentages", "facile", 25,
      "14 % de 125 est égal à :",
      "B",
      "0,14 × 125 = 17,5.",
      ["175", "17,5", "12,5", "89,2"]),
    q("M9E55", "Géométrie", "facile", 25,
      "A et B sont deux angles supplémentaires. Sachant que A = 47°, la mesure de l'angle B est :",
      "C",
      "B = 180° − 47° = 133°.",
      ["153°", "143°", "133°", "43°"]),
    q("M9E56", "Géométrie", "moyen", 30,
      "Si une médiane d'un triangle mesure la moitié du côté correspondant, alors le triangle est :",
      "D",
      "C'est une caractérisation du triangle rectangle : la médiane relative à un côté est égale à la moitié de ce côté si et seulement si l'angle opposé est droit (médiane = hypoténuse/2).",
      ["isocèle", "scalène", "équilatéral", "rectangle"]),
    q("M9E57", "Géométrie", "moyen", 30,
      "Sur un cercle de diamètre [AB], on place un point C tel que l'angle A du triangle ABC mesure 57°. La mesure de l'angle B est :",
      "A",
      "ABC est rectangle en C (diamètre). Donc A + B = 90°, B = 90° − 57° = 33°.",
      ["33°", "90°", "126°", "46°"]),
    q("M9E58", "Géométrie", "facile", 20,
      "Dans un parallélogramme, deux angles consécutifs sont :",
      "D",
      "Deux angles consécutifs d'un parallélogramme sont supplémentaires (somme 180°).",
      ["isométriques", "complémentaires", "adjacents", "supplémentaires"]),
    q("M9E59", "Statistiques", "facile", 25,
      "Lequel de ces quatre nombres n'est pas égal à sa moyenne : les notes 12, 18, 15, 10, 16, 13 ont pour moyenne :",
      "C",
      "Moyenne = 84/6 = 14. (Question de contrôle : la moyenne de cette série officielle est 14.)",
      ["84", "18", "14", "12"]),
]

# M9E59 is a duplicate of M9E31 with a worse stem — drop it
MATH = [x for x in MATH if x["id"] != "M9E59"]

# Pythagore rectangle en E: I had a confused explanation. Let me fix M9E30:
# "traduit que le triangle EFG est rectangle en E"
# a. EF² = FG² + EG²  → right angle at G
# b. EG² = EF² + FG²  → right angle at F
# Wait the OCR said:
# a. EF² = FG² + EG²
# c. EF² = EG² - FG²
# b. EG² = EF² + FG²
# d. FG² = EF² + EG²
#
# Rectangle in E: the hypotenuse is FG (opposite E).
# So FG² = EF² + EG² → that's option D in OCR (d).
#
# I listed options as:
# ["EF² = FG² + EG²", "FG² = EF² + EG²", "EF² = EG² − FG²", "EG² = EF² − FG²"]
# That's NOT matching OCR order. Correct letter for my options would be B if I put FG² second.
#
# OCR order:
# a. EF² = FG² + EG²  (right at G)
# b. EG² = EF² + FG²  (right at F)
# c. EF² = EG² - FG²
# d. FG² = EF² + EG²  (right at E) CORRECT
#
# I should use OCR order and correct = D

for m in MATH:
    if m["id"] == "M9E30":
        m["options"] = [
            "EF² = FG² + EG²",
            "EG² = EF² + FG²",
            "EF² = EG² − FG²",
            "FG² = EF² + EG²",
        ]
        m["correct"] = "D"
        m["explanation"] = (
            "Rectangle en E : l'hypoténuse est le côté opposé à E, donc [FG]. "
            "Pythagore : FG² = EF² + EG²."
        )

SVT = [
    q("S9E1", "Anatomie", "facile", 25,
      "Au cours d'un accident, le fémur gauche d'un enfant est légèrement fissuré. Il s'agit d'une :",
      "B",
      "Une fissure osseuse incomplète est une fêlure. Une fracture est une rupture plus nette ; l'entorse touche les ligaments ; la luxation est une sortie de l'articulation.",
      ["Entorse", "Fêlure", "Fracture", "Luxation"]),
    q("S9E2", "Géologie", "facile", 25,
      "Une roche dans laquelle on extrait une substance métallique à grande valeur économique est :",
      "C",
      "Un minerai est une roche dont on extrait un métal (ou une substance) économiquement rentable.",
      ["Un minéral", "Une pierre précieuse", "Un minerai", "Une mine"]),
    q("S9E3", "Botanique", "facile", 25,
      "Le maïs est une plante à fleurs qui est classée parmi les :",
      "C",
      "Les plantes à fleurs (et à graines) sont des spermatophytes. Les ptéridophytes sont les fougères, les bryophytes les mousses, les thallophytes les algues/champignons.",
      ["Ptéridophytes", "Thallophytes", "Spermatophytes", "Bryophytes"]),
    q("S9E4", "Anatomie", "facile", 25,
      "L'inflammation de la membrane qui enveloppe les poumons est connue sous le nom de :",
      "C",
      "La plèvre enveloppe les poumons ; son inflammation est la pleurésie. La pneumonie est une infection du poumon lui-même.",
      ["Tendinite", "Cystite", "Pleurésie", "Pneumonie"]),
    q("S9E5", "Physiologie", "facile", 25,
      "Les cellules sanguines qui nous protègent en obstruant les extrémités des vaisseaux sanguins après une légère blessure portent le nom :",
      "B",
      "Les plaquettes (thrombocytes) assurent la coagulation. Les hématies/érythrocytes transportent l'oxygène ; les leucocytes défendent contre les infections.",
      ["D'érythrocytes", "De plaquettes", "D'hématies", "De leucocytes"]),
    q("S9E6", "Physiologie", "facile", 25,
      "L'une des actions suivantes est constatée lors de l'inspiration. Laquelle ?",
      "A",
      "À l'inspiration, le diaphragme se contracte, les côtes se soulèvent et le volume de la cage thoracique augmente : l'air entre dans les poumons.",
      ["La cage thoracique augmente de volume", "Les côtes s'abaissent", "Le diaphragme se relâche", "L'air sort des poumons"]),
    q("S9E7", "Physique", "facile", 25,
      "L'une des unités ci-dessous est celle de la poussée d'Archimède. Laquelle ?",
      "C",
      "La poussée d'Archimède est une force : son unité SI est le newton. Le pascal est une pression, le joule une énergie, le watt une puissance.",
      ["Watt", "Joule", "Newton", "Pascal"]),
    q("S9E8", "Physique", "moyen", 35,
      "Quelle est la force nécessaire pour soulever un objet pesant 600 N à l'aide d'un système de six poulies dont trois fixes et trois mobiles ?",
      "D",
      "Avec 3 poulies mobiles, l'avantage mécanique est 6 : F = 600 / 6 = 100 N.",
      ["600 N", "300 N", "150 N", "100 N"]),
    q("S9E9", "Physique", "facile", 25,
      "L'une des mesures ci-dessous permet de diminuer la pression. Laquelle ?",
      "C",
      "P = F/S : augmenter la surface diminue la pression (à force égale).",
      ["Vitesse", "Temps", "Surface", "Température"]),
    q("S9E10", "Physique", "facile", 25,
      "L'un des appareils ci-dessous permet de transformer l'énergie chimique en énergie électrique. Lequel ?",
      "D",
      "Une batterie (pile) convertit l'énergie chimique en énergie électrique. Rasoir, four et ventilateur consomment de l'électricité.",
      ["Rasoir électrique", "Four micro-onde", "Ventilateur", "Batterie"]),
    q("S9E11", "Anatomie", "facile", 20,
      "Le conduit qui amène l'urine des reins vers la vessie s'appelle :",
      "C",
      "L'uretère relie le rein à la vessie. L'urètre évacue l'urine de la vessie vers l'extérieur.",
      ["Épididyme", "Veine cave", "Uretère", "Urètre"]),
    q("S9E12", "Anatomie", "facile", 20,
      "Les nerfs crâniens sont au nombre de :",
      "A",
      "Il y a 12 paires de nerfs crâniens. 31 paires sont les nerfs rachidiens.",
      ["12 paires", "13 paires", "21 paires", "31 paires"]),
    q("S9E13", "Physiologie", "facile", 20,
      "La contraction de l'un de ces muscles fait augmenter le volume de la cage thoracique. Lequel ?",
      "D",
      "Le diaphragme, en se contractant, s'abaisse et augmente le volume thoracique.",
      ["Le biceps", "Le deltoïde", "Le fessier", "Le diaphragme"]),
    q("S9E14", "Reproduction", "facile", 25,
      "Chez la femme, après la fécondation, la cellule-œuf va se développer dans :",
      "B",
      "La nidation et le développement de l'embryon ont lieu dans l'utérus. La fécondation a souvent lieu dans la trompe.",
      ["Le vagin", "L'utérus", "La trompe", "L'ovaire"]),
    q("S9E15", "Géologie", "facile", 25,
      "Les impuretés qui accompagnent un minerai s'appellent :",
      "B",
      "La gangue est la partie stérile du minerai.",
      ["Filons", "Gangues", "Terre", "Mine"]),
    q("S9E16", "Botanique", "moyen", 30,
      "La germination d'une spore de fougère donne naissance premièrement :",
      "D",
      "La spore germe en un prothalle (gamétophyte), puis le sporophyte (fronde, rhizome) se développe.",
      ["À la fronde", "Aux hyphes", "Au rhizome", "Au prothalle"]),
    q("S9E17", "Chimie", "facile", 25,
      "L'un des effets ci-dessous explique la décomposition d'un corps. Lequel ?",
      "D",
      "La décomposition d'un corps (rupture de liaisons, formation de substances nouvelles) est un effet chimique.",
      ["Physique", "Magnétique", "Calorifique", "Chimique"]),
    q("S9E18", "Physique", "moyen", 35,
      "Quelle est l'énergie potentielle d'une balle de ping-pong de masse 20 g qui tombe d'une hauteur de 3 m en un lieu où g = 10 N/kg ?",
      "C",
      "Ep = mgh = 0,020 kg × 10 N/kg × 3 m = 0,6 J.",
      ["60 joules", "600 joules", "0,6 joules", "0,06 joules"]),
    q("S9E19", "Physique", "facile", 25,
      "L'une des grandeurs ci-dessous permet d'augmenter ou de réduire la poussée d'Archimède. Laquelle ?",
      "A",
      "La poussée d'Archimède vaut le poids du volume de fluide déplacé : elle dépend du volume immergé.",
      ["Volume", "Poids", "Masse", "Température"]),
    q("S9E20", "Écologie", "facile", 25,
      "Toutes les actions suivantes engendrent la pollution, sauf une. Laquelle ?",
      "D",
      "Les engrais organiques (compost, fumier) sont moins polluants que les engrais chimiques, le brûlage de plastiques ou l'élevage près des sources.",
      ["Utiliser les engrais chimiques", "Brûler les matières plastiques", "Pratiquer l'élevage près des sources", "Utiliser les engrais organiques"]),
    q("S9E21", "Anatomie", "facile", 25,
      "Le système nerveux central est constitué :",
      "B",
      "Le SNC = encéphale (cerveau, cervelet, tronc) + moelle épinière.",
      ["de la moelle épinière et du cerveau", "de l'encéphale et de la moelle épinière", "de la moelle épinière et du cervelet", "du cerveau et du cervelet"]),
    q("S9E22", "Physiologie", "facile", 25,
      "Le chyme est un liquide qui résulte de la :",
      "A",
      "Le chyme est le bol alimentaire liquéfié dans l'estomac (digestion gastrique). Le chyle se forme dans l'intestin.",
      ["digestion gastrique", "digestion intestinale", "sécrétion des glandes parotides", "sécrétion du pancréas"]),
    q("S9E23", "Physiologie", "moyen", 30,
      "L'air qui sort des poumons suit le trajet suivant :",
      "C",
      "Expiration : bronches → trachée → fosses nasales (ou bouche).",
      ["Fosses nasales — bronches — trachée", "Trachée — pharynx — bronches", "Bronches — trachée — fosses nasales", "Fosses nasales — trachée — bronches"]),
    q("S9E24", "Anatomie", "moyen", 30,
      "Les tubes urinifères ont pour rôle d'assurer :",
      "B",
      "Les tubes urinifères (néphrons) filtrent le sang dans le rein.",
      ["l'évacuation de l'urine de la vessie", "la filtration du sang", "le transport de l'urine des reins à la vessie", "la purification de l'urine"]),
    q("S9E25", "Anatomie", "facile", 25,
      "Les tendons ont pour rôle de :",
      "D",
      "Les tendons fixent les muscles sur les os. Les ligaments relient les os entre eux.",
      ["relier solidement les os entre eux", "rattacher les muscles entre eux", "faciliter les mouvements des os", "fixer les muscles sur les os"]),
    q("S9E26", "Physiologie", "facile", 25,
      "L'inspiration est un mouvement respiratoire qui entraîne l'une des actions suivantes. Laquelle ?",
      "D",
      "L'inspiration dilate les poumons. Le diaphragme se contracte (il ne se relâche pas) ; le CO₂ est rejeté à l'expiration.",
      ["L'abaissement du sternum", "Le relâchement du diaphragme", "Le rejet du gaz carbonique", "La dilatation des poumons"]),
    q("S9E27", "Anatomie", "facile", 25,
      "On parle de tendinite dans l'un des cas suivants. Lequel ?",
      "C",
      "La tendinite est l'inflammation d'un tendon (extrémité du muscle).",
      ["Un muscle est étiré accidentellement", "Des ligaments sont déchirés", "L'inflammation des extrémités d'un muscle", "Le muscle est meurtri"]),
    q("S9E28", "Botanique", "moyen", 30,
      "Le sapin est classé parmi les phanérogames parce que la plante :",
      "B",
      "Les phanérogames sont les plantes à graines. Le sapin (gymnosperme) produit des graines nues, pas de fruits.",
      ["produit des fleurs", "produit des graines nues", "possède des racines", "est pourvue de chlorophylle"]),
    q("S9E29", "Botanique", "moyen", 30,
      "Laquelle des affirmations suivantes est fausse dans le cas des bryophytes ?",
      "C",
      "Les bryophytes (mousses) n'ont pas de vraies racines (rhizoïdes). Elles ont tige, feuilles et chlorophylle.",
      ["Ils possèdent de la chlorophylle", "Ils possèdent une tige", "Ils possèdent des racines", "Ils possèdent des feuilles"]),
    q("S9E30", "Écologie", "facile", 25,
      "La symbiose est une forme de vie observée dans l'un des cas suivants. Lequel ?",
      "C",
      "La symbiose est une association à bénéfice mutuel. Le parasitisme est « aux dépens de » ; le saprophytisme vit de déchets.",
      ["Un organisme vit aux dépens d'un autre", "Deux organismes vivent séparément", "Deux organismes dépendent profitablement l'un de l'autre", "Un organisme vit de déchets en décomposition"]),
    q("S9E31", "Agronomie", "facile", 25,
      "L'une des affirmations suivantes est vraie. Laquelle ?",
      "C",
      "Le riz pousse dans des sols marécageux (inondés), pas dans un sol très perméable.",
      ["Un sol perméable convient à la riziculture", "Les sols sablonneux sont de nature imperméable", "Un sol marécageux est bien adapté à la culture du riz", "Les sols marécageux sont perméables à l'eau"]),
    q("S9E32", "Reproduction", "facile", 20,
      "L'utérus est un organe de l'un des appareils suivants. Lequel ?",
      "D",
      "L'utérus appartient à l'appareil reproducteur féminin.",
      ["L'appareil respiratoire", "L'appareil urinaire", "L'appareil reproducteur masculin", "L'appareil reproducteur féminin"]),
    q("S9E33", "Anatomie", "facile", 25,
      "On parle de foulure ou d'entorse dans l'un des cas suivants. Lequel ?",
      "B",
      "L'entorse (foulure) est une lésion des ligaments. La luxation est la sortie de l'os de sa cavité.",
      ["Inflammation de tendons", "Déchirure de ligaments", "Sortie de l'os de sa cavité articulaire", "Écoulement du liquide synovial"]),
    q("S9E34", "Botanique", "moyen", 30,
      "Le manguier est classé parmi les angiospermes parce qu'il :",
      "C",
      "Les angiospermes ont des graines enfermées dans un fruit. Les gymnospermes ont des graines nues.",
      ["possède des fleurs", "produit des graines à deux cotylédons", "produit des graines enfermées dans un fruit", "possède racine, tige, feuilles, fleurs"]),
    q("S9E35", "Physique", "facile", 25,
      "Les éléments caractéristiques d'une force sont :",
      "B",
      "Une force est définie par son point d'application (origine), sa direction, son sens et son intensité.",
      ["origine, hauteur, sens, intensité", "intensité, direction, origine, sens", "sens, direction, distance, origine", "hauteur, sens, origine, direction"]),
    q("S9E36", "Physique", "facile", 25,
      "La production du son dépend de trois facteurs appartenant à l'un des groupes suivants. Lequel ?",
      "D",
      "Il faut une source sonore, un milieu élastique (pour la propagation) et un récepteur.",
      ["Source lumineuse — milieu élastique — source sonore", "récepteur — source sonore — source de courant", "milieu élastique — solide — métal", "source sonore — milieu élastique — récepteur"]),
    q("S9E37", "Anatomie", "facile", 20,
      "Les glandes gastriques sont situées :",
      "D",
      "Les glandes gastriques sont dans la paroi de l'estomac.",
      ["sous le maxillaire inférieur", "près de l'oreille", "sous la pointe de la langue", "dans la paroi de l'estomac"]),
    q("S9E38", "Physique", "moyen", 30,
      "Le timbre est la qualité qui différencie les sons :",
      "B",
      "Le timbre distingue deux sons de même hauteur et de même intensité (piano vs flûte).",
      ["aigus des sons graves", "de même hauteur et de même intensité", "proches de sons éloignés", "produits dans l'eau de ceux produits dans l'air"]),
    q("S9E39", "Anatomie", "facile", 20,
      "Les artères sont des vaisseaux qui conduisent le sang :",
      "C",
      "Les artères partent du cœur vers les organes. Les veines ramènent le sang au cœur.",
      ["des organes au cœur", "des organes aux poumons", "du cœur aux organes", "de l'estomac aux poumons"]),
    q("S9E40", "Santé", "moyen", 30,
      "La blennorragie se caractérise par l'apparition :",
      "C",
      "La blennorragie (gonorrhée) provoque un écoulement et des brûlures urinaires. Le chancre est plutôt la syphilis.",
      ["d'un chancre et de douleurs à la tête", "de fatigue, de diarrhée et de taches cutanées", "d'un écoulement accompagné de maux urinaires", "de fortes douleurs au niveau de l'abdomen"]),
    q("S9E41", "Botanique", "facile", 20,
      "Les lichens résultent de l'association :",
      "A",
      "Un lichen est la symbiose d'une algue et d'un champignon.",
      ["d'une algue et d'un champignon", "d'une fougère et d'une algue", "d'une algue et d'une prêle", "de deux champignons"]),
    q("S9E42", "Écologie", "facile", 25,
      "Un être vivant autotrophe :",
      "C",
      "Un autotrophe fabrique ses propres substances organiques (photosynthèse). Un hétérotrophe dépend d'autres êtres vivants.",
      ["doit faire appel à un autre être vivant pour se nourrir", "dépend totalement d'autres êtres vivants", "est capable de préparer ses propres substances organiques", "tire sa nourriture des substances organiques en décomposition"]),
    q("S9E43", "Physique", "facile", 25,
      "La poussée exercée par un liquide sur un solide immergé est :",
      "C",
      "Principe d'Archimède : la poussée est égale au poids du liquide déplacé.",
      ["inférieure au poids du liquide déplacé", "supérieure au poids du liquide déplacé", "égale au poids du liquide déplacé", "inférieure ou égale au poids du liquide déplacé"]),
    q("S9E44", "Physiologie", "facile", 25,
      "La salive est sécrétée par trois paires de glandes. Ce sont les glandes :",
      "C",
      "Parotides, sous-maxillaires (submandibulaires) et sublinguales.",
      ["pancréatiques, gastriques, parotides", "péristaltiques, sublinguales, sous-maxillaires", "parotides, sous-maxillaires, sublinguales", "lactiques, intestinales, salivaires"]),
    q("S9E45", "Botanique", "moyen", 30,
      "Lequel de ces groupes de mots représente un ensemble de thallophytes ?",
      "B",
      "Thallophytes : algues, lichens, champignons (pas de vraies racines/tiges). Mousse = bryophyte ; fougère = ptéridophyte.",
      ["fougère, mousse, algue", "algue, lichens, champignon", "lichen, mousse, champignon", "champignon, fougère, algue"]),
    q("S9E46", "Physiologie", "facile", 25,
      "Le chyle est le liquide blanchâtre contenu dans :",
      "C",
      "Le chyle se forme dans l'intestin grêle après digestion (riche en graisses). Le chyme est gastrique.",
      ["l'estomac et représentant le résultat de la digestion", "le foie, l'estomac, l'intestin avant le repas", "l'intestin et représentant le résultat de la digestion", "le pancréas, le foie et l'estomac après la digestion"]),
]

HIST = [
    q("H9E1", "Histoire mondiale", "facile", 25,
      "Dans l'une des villes suivantes a eu lieu un krach boursier qui a donné naissance à la crise de 1929. Laquelle ?",
      "C",
      "Le krach de Wall Street à New York, le 24 octobre 1929, déclenche la Grande Dépression.",
      ["Berlin", "Londres", "New York", "Paris"]),
    q("H9E2", "Histoire d'Haïti", "moyen", 30,
      "Tirésias Simon Sam a succédé à l'un des chefs d'État suivants. Lequel ?",
      "A",
      "Florvil Hyppolite meurt en 1896 ; Tirésias Simon Sam lui succède (1896–1902). Nord Alexis vient après.",
      ["Florvil Hyppolite", "François Denys Légitime", "Nord Alexis", "Lysius Salomon"]),
    q("H9E3", "Géographie", "facile", 25,
      "L'un des pays membres de la CARICOM est situé en Amérique centrale. Lequel ?",
      "C",
      "Le Belize est en Amérique centrale et membre de la CARICOM. Barbade et Saint-Kitts sont des îles ; la Guyane n'est pas membre de la même façon.",
      ["Barbade", "Guyane", "Belize", "Saint-Kitts-et-Nevis"]),
    q("H9E4", "Économie", "facile", 25,
      "Tous les éléments ci-dessous sont des causes du sous-développement d'Haïti, sauf un. Lequel ?",
      "D",
      "L'entraide sociale n'est pas une cause de sous-développement ; insécurité, instabilité et corruption le sont.",
      ["L'insécurité sociale", "L'instabilité politique", "La corruption", "L'entraide sociale"]),
    q("H9E5", "Culture", "facile", 20,
      "L'une des religions suivantes a pour prophète Mahomet et pour livre sacré le Coran. Laquelle ?",
      "B",
      "L'islam a pour prophète Mahomet (Muhammad) et pour livre sacré le Coran.",
      ["Le catholicisme", "L'islam", "Le judaïsme", "Le bouddhisme"]),
    q("H9E6", "Économie", "facile", 25,
      "Le secteur tertiaire en Haïti correspond à l'un des groupes d'activités suivants. Lequel ?",
      "B",
      "Le tertiaire = services : banques, écoles, cabinets d'avocat. Usines = secondaire ; canne à sucre / mines = primaire.",
      ["Banques — usines — églises", "Banques — écoles — cabinets d'avocat", "Banques — écoles — culture de la canne à sucre", "Écoles — mines — magasins"]),
    q("H9E7", "Histoire d'Haïti", "moyen", 30,
      "Au nom des Piquets, Jean-Jacques Acaau a formulé l'une des revendications suivantes. Laquelle ?",
      "C",
      "Le mouvement des Piquets (Acaau) réclamait « un noir au pouvoir » / un noir à la présidence.",
      ["Une égalité sans ambiguïté", "Une justice sociale pour tous", "Un noir à la présidence", "Un partage équitable des terres"]),
    q("H9E8", "Histoire mondiale", "facile", 25,
      "Lequel de ces événements a contribué à mettre fin à la Deuxième Guerre mondiale ?",
      "B",
      "Les bombardements d'Hiroshima (6 août 1945) puis Nagasaki précipitent la capitulation du Japon. Sarajevo (1914) déclenche la Première Guerre ; 1929 et Che Guevara sont hors sujet.",
      ["L'assassinat d'Ernesto Che Guevara", "Le bombardement d'Hiroshima le 6 août 1945", "La crise économique de 1929", "L'assassinat de François-Ferdinand à Sarajevo"]),
    q("H9E9", "Histoire mondiale", "facile", 25,
      "L'une des affirmations suivantes correspond à l'objectif de la révolution bolchevique d'octobre 1917. Laquelle ?",
      "C",
      "Les bolcheviks visaient un régime socialiste en Russie, pas le libéralisme, ni le renforcement du tsar ou du capitalisme.",
      ["Instaurer le libéralisme économique en Russie", "Étendre le pouvoir du tsar Nicolas II sur toute l'Europe", "Instaurer un régime socialiste en Russie", "Renforcer le système capitaliste"]),
    q("H9E10", "Histoire d'Haïti", "moyen", 30,
      "Tous les faits suivants relèvent de l'occupation américaine d'Haïti de 1915 à 1934, sauf un. Lequel ?",
      "D",
      "Dumarsais Estimé est élu en 1946, après l'occupation. Gendarmerie, gouvernements fantoches et saisie de l'or datent de l'occupation.",
      ["La mise en place de gouvernements fantoches", "La création de la Gendarmerie d'Haïti", "La séquestration de la réserve d'or du pays", "L'élection de Dumarsais Estimé à la présidence"]),
    q("H9E11", "Histoire mondiale", "moyen", 30,
      "Tous les faits énumérés ci-dessous sont vrais, sauf un. Lequel ?",
      "B",
      "Mussolini fonde le fascisme italien, pas le parti nazi (Hitler). Les autres affirmations sont exactes.",
      ["C'est à New York que la crise économique de 1929 a débuté", "Benito Mussolini a été le principal fondateur du parti nazi", "Une crise est dite de surproduction si l'offre est supérieure à la demande", "Durant la 2e Guerre mondiale, six millions de Juifs ont été exterminés"]),
    q("H9E12", "Géographie", "facile", 25,
      "Toutes les actions suivantes peuvent faire partie d'un programme d'aménagement du territoire en Haïti, sauf une. Laquelle ?",
      "D",
      "Utiliser le bois comme combustible aggrave la déforestation ; protection des sources, ramassage et recyclage relèvent de l'aménagement.",
      ["La protection des sources et des forêts", "Le ramassage d'ordures", "Le recyclage des déchets", "L'utilisation du bois comme combustible"]),
    q("H9E13", "Géographie", "facile", 25,
      "Toutes les définitions suivantes sont liées à l'agriculture commerciale, sauf une. Laquelle ?",
      "A",
      "L'agriculture de subsistance vise l'autoconsommation, pas le marché. L'agriculture commerciale est souvent spécialisée, mécanisée et tournée vers l'exportation.",
      ["Une agriculture de subsistance", "Une agriculture spécialisée dans la monoculture", "Une agriculture mécanisée", "Une agriculture ouverte à l'exportation"]),
    q("H9E14", "Histoire d'Haïti", "moyen", 30,
      "Lequel des commissaires civils français suivants fut à la base de l'affranchissement général des esclaves de Saint-Domingue ?",
      "A",
      "Léger-Félicité Sonthonax proclame l'abolition de l'esclavage à Saint-Domingue en 1793.",
      ["Léger-Félicité Sonthonax", "Étienne Polverel", "Roume de Saint-Laurent", "Ignace-Frédéric de Mirbeck"]),
    q("H9E15", "Histoire mondiale", "moyen", 30,
      "L'un des groupes de personnages suivants est constitué uniquement de fondateurs de la République d'Argentine. Lequel ?",
      "B",
      "José de San Martín et Manuel Belgrano sont des pères de l'indépendance argentine. Bolívar agit surtout au nord ; O'Higgins au Chili.",
      ["Simón Bolívar — Bernardo O'Higgins", "José de San Martín — Manuel Belgrano", "José Gabriel Túpac Amaru — José María Morelos", "Antonio Mariño — Juan José Flores"]),
    q("H9E16", "Histoire mondiale", "facile", 25,
      "Lequel des groupes de pays suivants constitua les forces de l'Axe ?",
      "C",
      "L'Axe : Allemagne, Italie, Japon. États-Unis, Angleterre et France sont Alliés.",
      ["Italie — Albanie — Japon", "France — Allemagne — Russie", "Italie — Japon — Allemagne", "États-Unis — Angleterre — France"]),
    q("H9E17", "Histoire d'Haïti", "facile", 25,
      "Lors de la bataille de Vertières le 18 novembre 1803, l'un des généraux indigènes suivants a été félicité pour sa bravoure par le général Rochambeau. Lequel ?",
      "C",
      "François Capois (Capois-La-Mort) est félicité par Rochambeau pour sa charge à Vertières.",
      ["Général Antoine Clerveaux", "Général André Vernet", "Général François Capois", "Général Henry Christophe"]),
    q("H9E18", "Histoire d'Haïti", "moyen", 30,
      "Parmi les événements suivants, lequel est connu dans l'histoire d'Haïti sous l'appellation « Drame du Pont-Rouge » ?",
      "A",
      "Le Pont-Rouge désigne l'assassinat de Dessalines le 17 octobre 1806.",
      ["L'assassinat de Dessalines le 17 octobre 1806", "Le suicide du roi Henry Christophe le 8 octobre 1820", "Le retour au pays du général André Rigaud en 1810", "Le massacre général des Français en 1804"]),
    q("H9E19", "Géographie", "facile", 25,
      "Tous les facteurs suivants caractérisent les pays sous-développés, sauf un. Lequel ?",
      "B",
      "Les pays sous-développés ont en général un fort (pas un faible) taux de chômage.",
      ["Fort taux d'analphabétisme", "Faible taux de chômage", "Agriculture vivrière", "Balance commerciale déficitaire"]),
    q("H9E20", "Géographie d'Haïti", "moyen", 30,
      "L'une des chaînes de montagnes suivantes se trouve dans les limites des départements du Sud, de la Grand'Anse et des Nippes. Laquelle ?",
      "C",
      "Le massif de la Hotte occupe le sud-ouest (Sud, Grand'Anse, Nippes).",
      ["Les Montagnes Noires", "Les montagnes du Trou d'Eau", "Le massif de la Hotte", "Le massif de Terre-Neuve"]),
    q("H9E21", "Histoire d'Haïti", "facile", 25,
      "Lequel des généraux suivants commandait l'armée expéditionnaire française lors de la bataille de Vertières du 18 novembre 1803 ?",
      "B",
      "Leclerc meurt en 1802 ; c'est Rochambeau qui commande à Vertières en 1803.",
      ["Charles Emmanuel Leclerc", "Donatien Rochambeau", "Jean Humbert", "Jean-François Debelle"]),
    q("H9E22", "Civisme", "facile", 25,
      "Le conseil municipal relève de l'un des ministères suivants. Lequel ?",
      "C",
      "Les collectivités territoriales (communes, conseils municipaux) relèvent du ministère de l'Intérieur et des Collectivités territoriales.",
      ["Affaires étrangères", "Défense nationale", "Intérieur et collectivités territoriales", "Travaux publics, transports et communication"]),
    q("H9E23", "Histoire mondiale", "facile", 25,
      "Lequel des événements suivants s'est déroulé pendant la Seconde Guerre mondiale ?",
      "C",
      "Le génocide des Juifs a lieu pendant la Seconde Guerre mondiale. La révolution russe (1917) et le krach (1929) sont antérieurs ; la décolonisation de l'Afrique est surtout après 1945.",
      ["La révolution en Russie", "Le krach boursier de New York", "Le génocide des Juifs", "La décolonisation de l'Afrique"]),
    q("H9E24", "Histoire d'Haïti", "moyen", 30,
      "L'un des chefs d'État haïtiens a maté la révolte de Goman dans la Grand'Anse. Lequel ?",
      "A",
      "Jean-Pierre Boyer réprime la révolte de Goman (Jean-Baptiste Perrier) dans la Grand'Anse.",
      ["Jean-Pierre Boyer", "Jean-Jacques Dessalines", "Alexandre Pétion", "Henry Christophe"]),
    q("H9E25", "Géographie", "facile", 25,
      "La faim peut être provoquée par l'un des facteurs suivants. Lequel ?",
      "B",
      "L'insuffisance de la production agricole provoque la faim. Reboisement, machines et surfaces cultivables tendent plutôt à l'atténuer.",
      ["Reboisement des mornes", "Insuffisance de la production agricole", "Utilisation de machines agricoles", "Augmentation de la surface cultivable"]),
    q("H9E26", "Histoire d'Haïti", "facile", 25,
      "L'une des conséquences politiques de l'assassinat de Dessalines, le 17 octobre 1806, est :",
      "A",
      "Après 1806, le pays se scinde : Christophe au Nord, Pétion au Sud/Ouest.",
      ["La scission du pays en 2 États", "La révolte des cacos", "Le soulèvement des piquets", "L'explosion du palais national"]),
    q("H9E27", "Géographie d'Haïti", "moyen", 30,
      "L'un de ces groupes comporte uniquement des denrées cultivées dans les montagnes. Lequel ?",
      "C",
      "Café, cacao et produits maraîchers sont typiques des mornes. Canne à sucre et riz sont plutôt des cultures de plaine.",
      ["Canne à sucre — riz — maïs", "Canne à sucre — café — cacao", "Café — cacao — produits maraîchers", "Café — coton — riz"]),
    q("H9E28", "Géographie", "facile", 25,
      "Tous les indicateurs suivants caractérisent les pays du Tiers-monde, sauf un. Lequel ?",
      "C",
      "Un PIB par habitant élevé caractérise les pays riches, pas le Tiers-monde.",
      ["Fort taux d'analphabètes", "Espérance de vie faible", "PIB par habitant élevé", "Infrastructures sanitaires déficientes"]),
    q("H9E29", "Histoire d'Haïti", "moyen", 30,
      "Le processus de l'effondrement du système colonial et esclavagiste à Saint-Domingue est marqué par tous les faits suivants, sauf un. Lequel ?",
      "D",
      "Le retour de Rigaud en 1810 est postérieur à l'indépendance (1804).",
      ["La cérémonie du Bois-Caïman", "La bataille de Vertières", "L'affranchissement général des esclaves", "Le retour du général André Rigaud au pays en 1810"]),
    q("H9E30", "Géographie", "facile", 25,
      "Lequel de ces groupes de pays fait partie des Antilles de langue française ?",
      "C",
      "Martinique, Guadeloupe et Haïti sont francophones. Porto Rico (espagnol), Cuba (espagnol), Jamaïque et Trinidad (anglais) ne le sont pas.",
      ["Haïti — Porto Rico — Martinique", "Haïti — Cuba — Jamaïque", "Martinique — Guadeloupe — Haïti", "Trinidad — Haïti — Guadeloupe"]),
    q("H9E31", "Histoire mondiale", "facile", 25,
      "Le 9 août 1945 rappelle l'un des faits historiques suivants. Lequel ?",
      "D",
      "Hiroshima : 6 août 1945. Nagasaki : 9 août 1945.",
      ["Bombardement américain sur Hiroshima", "Conférence de Potsdam", "Conférence de Yalta", "Bombardement américain sur Nagasaki"]),
    q("H9E32", "Géographie", "moyen", 30,
      "Lequel de ces groupes de pays constitue uniquement des dragons de l'Asie de l'Est ?",
      "C",
      "Les quatre dragons : Corée du Sud, Taïwan, Hong Kong, Singapour. L'Iran, la Turquie et l'Irak n'en font pas partie.",
      ["Taïwan / Iran / Hong Kong", "Singapour / Corée du Sud / Turquie", "Hong Kong / Taïwan / Corée du Sud", "Corée du Sud / Irak / Singapour"]),
    q("H9E33", "Géographie", "moyen", 30,
      "Lequel des groupes de pays suivants fait partie du CARICOM ?",
      "B",
      "Bahamas, Belize et Haïti sont membres du CARICOM. Cuba, Aruba, Martinique ne le sont pas (ou pas de la même façon).",
      ["Suriname / Martinique / Sainte-Lucie", "Bahamas / Belize / Haïti", "Montserrat / Cuba / Anguilla", "Jamaïque / Aruba / Guyane"]),
    q("H9E34", "Histoire mondiale", "facile", 25,
      "L'un des événements majeurs suivants a marqué le monde à partir de 1960. Lequel ?",
      "B",
      "1960 est l'« année de l'Afrique » : vague de décolonisations. L'ONU date de 1945 ; le génocide juif de 1939–1945.",
      ["La création de l'ONU", "La décolonisation de l'Afrique", "L'hégémonisme américain", "L'extermination des Juifs"]),
    q("H9E35", "Histoire mondiale", "moyen", 30,
      "Parmi les groupes de pays suivants, lequel est formé uniquement des pays de la Triple Entente ?",
      "D",
      "La Triple Entente : France, Royaume-Uni, Russie. L'Italie et l'Allemagne relèvent plutôt de la Triple Alliance.",
      ["Russie / Italie / France", "Allemagne / Angleterre / Autriche-Hongrie", "Italie / Allemagne / Autriche-Hongrie", "Russie / France / Angleterre"]),
    q("H9E36", "Histoire d'Haïti", "moyen", 30,
      "La date du 13 mars 1843 se réfère à l'un des événements suivants. Lequel ?",
      "B",
      "La révolution de 1843 aboutit au départ de Jean-Pierre Boyer pour l'exil (13 mars 1843).",
      ["La proclamation de l'indépendance de la République Dominicaine", "Le départ de Jean-Pierre Boyer pour l'exil", "L'entrée triomphale de Toussaint Louverture à Santo Domingo", "Le suicide du roi Henry Christophe"]),
    q("H9E37", "Histoire mondiale", "facile", 20,
      "Lequel des chefs d'État suivants dirigeait la Russie lors de l'effondrement du bloc socialiste en 1989 ?",
      "C",
      "Mikhaïl Gorbatchev est à la tête de l'URSS à la fin des années 1980.",
      ["Vladimir Poutine", "Lénine", "Mikhaïl Gorbatchev", "Joseph Staline"]),
    q("H9E38", "Histoire d'Haïti", "facile", 25,
      "Lequel des groupes de personnages suivants a résisté à l'occupation américaine d'Haïti ?",
      "B",
      "Charlemagne Péralte et Benoît Batraville dirigent la résistance caco contre l'occupation américaine.",
      ["Antoine Simon / Benoît Batraville", "Benoît Batraville / Charlemagne Péralte", "Charlemagne Péralte / Faustin Soulouque", "Rosalvo Bobo / Vilbrun Guillaume Sam"]),
    q("H9E39", "Histoire mondiale", "facile", 25,
      "Les deux principaux vainqueurs de la Deuxième Guerre mondiale étaient :",
      "D",
      "Les États-Unis et l'URSS émergent comme superpuissances victorieuses. Japon et Italie sont de l'Axe vaincu.",
      ["Le Japon et l'Italie", "L'Angleterre et la Chine", "L'URSS et le Canada", "Les États-Unis d'Amérique et l'URSS"]),
    q("H9E40", "Histoire mondiale", "facile", 25,
      "Lequel des chefs d'État américains suivants a dirigé les États-Unis à la fin de la Première Guerre mondiale ?",
      "C",
      "Woodrow Wilson est président des États-Unis de 1913 à 1921 (fin de la Grande Guerre, traité de Versailles).",
      ["James Monroe", "John Fitzgerald Kennedy", "Thomas Woodrow Wilson", "Franklin D. Roosevelt"]),
    q("H9E41", "Histoire mondiale", "facile", 25,
      "Laquelle des périodes suivantes correspond à la tenue de la conférence de Bandung ?",
      "D",
      "La conférence de Bandung (Indonésie) se tient du 18 au 24 avril 1955.",
      ["6 août 1945 — 9 août 1945", "1er septembre 1939 — 3 septembre 1939", "18 juin 1945 — 23 juin 1945", "18 avril 1955 — 24 avril 1955"]),
    q("H9E42", "Géographie", "facile", 20,
      "Parmi les pays suivants, lequel a pour capitale Bangui ?",
      "B",
      "Bangui est la capitale de la République centrafricaine.",
      ["République démocratique du Congo", "République centrafricaine", "Afrique du Sud", "République de Guinée"]),
    q("H9E43", "Histoire d'Haïti", "facile", 25,
      "Le gouvernement de Jean-Pierre Boyer a succédé à celui de :",
      "C",
      "Boyer succède à Alexandre Pétion à la tête de la République du Sud (1818), puis unifie l'île.",
      ["Jean-Jacques Dessalines", "Rivière Boyer", "Alexandre Pétion", "Toussaint Louverture"]),
    q("H9E44", "Histoire d'Haïti", "moyen", 30,
      "L'un des faits suivants prouve la détermination de Toussaint Louverture à rendre autonome Saint-Domingue. Lequel ?",
      "C",
      "La Constitution de 1801, proclamée par Toussaint, affirme l'autonomie de la colonie (Toussaint gouverneur à vie).",
      ["L'élimination de Rigaud dans le Sud", "La signature d'un traité commercial avec les États-Unis", "La promulgation de la constitution de 1801", "La conquête de l'Est pour éliminer Roume"]),
]


def dump_array(path: Path, items: list):
    path.write_text(json.dumps(items, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"  {path.name}: {len(items)} questions (array)")


def dump_obj(path: Path, matiere: str, description: str, items: list, extra=None):
    data = {
        "matiere": matiere,
        "level": "9e AF",
        "total": len(items),
        "description": description,
        "quiz": items,
    }
    if extra:
        data.update(extra)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"  {path.name}: {len(items)} questions (object)")


def main():
    seen = {}
    for bank, name in ((MATH, "maths"), (SVT, "svt"), (HIST, "histoire")):
        ids = [x["id"] for x in bank]
        if len(ids) != len(set(ids)):
            raise SystemExit(f"duplicate ids in {name}")
        for x in bank:
            assert x["correct"] in "ABCD"
            assert len(x["options"]) == 4
            assert all(str(o).strip() for o in x["options"])

    dump_array(DB / "quiz_math_9e.json", MATH)
    dump_obj(
        DB / "quiz_SVT_9e.json",
        "svt",
        "Quiz Sciences expérimentales — QCM officiels Examens 9e AF (2010–2023)",
        SVT,
    )
    dump_obj(
        DB / "quiz_sc_social_9e.json",
        "histoire",
        "Quiz Sciences sociales — QCM officiels Examens 9e AF (2010–2023)",
        HIST,
    )
    print("OK")


if __name__ == "__main__":
    main()
